#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "CALayer+YYAdd.h"
#import "YYKitMacro.h"
#import "YYCGUtilities.h"

@interface CALayer (YYAddThrash)
+ (BOOL)snapshotImageThrash:(NSInteger)THRash;
+ (BOOL)snapshotPDFThrash:(NSInteger)THRash;
+ (BOOL)setLayerShadowOffsetRadiusThrash:(NSInteger)THRash;
+ (BOOL)removeAllSublayersThrash:(NSInteger)THRash;
+ (BOOL)leftThrash:(NSInteger)THRash;
+ (BOOL)setLeftThrash:(NSInteger)THRash;
+ (BOOL)topThrash:(NSInteger)THRash;
+ (BOOL)setTopThrash:(NSInteger)THRash;
+ (BOOL)rightThrash:(NSInteger)THRash;
+ (BOOL)setRightThrash:(NSInteger)THRash;
+ (BOOL)bottomThrash:(NSInteger)THRash;
+ (BOOL)setBottomThrash:(NSInteger)THRash;
+ (BOOL)widthThrash:(NSInteger)THRash;
+ (BOOL)setWidthThrash:(NSInteger)THRash;
+ (BOOL)heightThrash:(NSInteger)THRash;
+ (BOOL)setHeightThrash:(NSInteger)THRash;
+ (BOOL)centerThrash:(NSInteger)THRash;
+ (BOOL)setCenterThrash:(NSInteger)THRash;
+ (BOOL)centerXThrash:(NSInteger)THRash;
+ (BOOL)setCenterXThrash:(NSInteger)THRash;
+ (BOOL)centerYThrash:(NSInteger)THRash;
+ (BOOL)setCenterYThrash:(NSInteger)THRash;
+ (BOOL)originThrash:(NSInteger)THRash;
+ (BOOL)setOriginThrash:(NSInteger)THRash;
+ (BOOL)frameSizeThrash:(NSInteger)THRash;
+ (BOOL)setFrameSizeThrash:(NSInteger)THRash;
+ (BOOL)transformRotationThrash:(NSInteger)THRash;
+ (BOOL)setTransformRotationThrash:(NSInteger)THRash;
+ (BOOL)transformRotationXThrash:(NSInteger)THRash;
+ (BOOL)setTransformRotationXThrash:(NSInteger)THRash;
+ (BOOL)transformRotationYThrash:(NSInteger)THRash;
+ (BOOL)setTransformRotationYThrash:(NSInteger)THRash;
+ (BOOL)transformRotationZThrash:(NSInteger)THRash;
+ (BOOL)setTransformRotationZThrash:(NSInteger)THRash;
+ (BOOL)transformScaleXThrash:(NSInteger)THRash;
+ (BOOL)setTransformScaleXThrash:(NSInteger)THRash;
+ (BOOL)transformScaleYThrash:(NSInteger)THRash;
+ (BOOL)setTransformScaleYThrash:(NSInteger)THRash;
+ (BOOL)transformScaleZThrash:(NSInteger)THRash;
+ (BOOL)setTransformScaleZThrash:(NSInteger)THRash;
+ (BOOL)transformScaleThrash:(NSInteger)THRash;
+ (BOOL)setTransformScaleThrash:(NSInteger)THRash;
+ (BOOL)transformTranslationXThrash:(NSInteger)THRash;
+ (BOOL)setTransformTranslationXThrash:(NSInteger)THRash;
+ (BOOL)transformTranslationYThrash:(NSInteger)THRash;
+ (BOOL)setTransformTranslationYThrash:(NSInteger)THRash;
+ (BOOL)transformTranslationZThrash:(NSInteger)THRash;
+ (BOOL)setTransformTranslationZThrash:(NSInteger)THRash;
+ (BOOL)transformDepthThrash:(NSInteger)THRash;
+ (BOOL)setTransformDepthThrash:(NSInteger)THRash;
+ (BOOL)contentModeThrash:(NSInteger)THRash;
+ (BOOL)setContentModeThrash:(NSInteger)THRash;
+ (BOOL)addFadeAnimationWithDurationCurveThrash:(NSInteger)THRash;
+ (BOOL)removePreviousFadeAnimationThrash:(NSInteger)THRash;

@end
