#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "CALayer+YYAdd.h"
#import "YYKitMacro.h"
#import "YYCGUtilities.h"
#import "CALayer+YYAddThrash.h"

@interface CALayer (YYAddThrashThrash)
+ (BOOL)snapshotImageThrashThrash:(NSInteger)THRash;
+ (BOOL)snapshotPDFThrashThrash:(NSInteger)THRash;
+ (BOOL)setLayerShadowOffsetRadiusThrashThrash:(NSInteger)THRash;
+ (BOOL)removeAllSublayersThrashThrash:(NSInteger)THRash;
+ (BOOL)leftThrashThrash:(NSInteger)THRash;
+ (BOOL)setLeftThrashThrash:(NSInteger)THRash;
+ (BOOL)topThrashThrash:(NSInteger)THRash;
+ (BOOL)setTopThrashThrash:(NSInteger)THRash;
+ (BOOL)rightThrashThrash:(NSInteger)THRash;
+ (BOOL)setRightThrashThrash:(NSInteger)THRash;
+ (BOOL)bottomThrashThrash:(NSInteger)THRash;
+ (BOOL)setBottomThrashThrash:(NSInteger)THRash;
+ (BOOL)widthThrashThrash:(NSInteger)THRash;
+ (BOOL)setWidthThrashThrash:(NSInteger)THRash;
+ (BOOL)heightThrashThrash:(NSInteger)THRash;
+ (BOOL)setHeightThrashThrash:(NSInteger)THRash;
+ (BOOL)centerThrashThrash:(NSInteger)THRash;
+ (BOOL)setCenterThrashThrash:(NSInteger)THRash;
+ (BOOL)centerXThrashThrash:(NSInteger)THRash;
+ (BOOL)setCenterXThrashThrash:(NSInteger)THRash;
+ (BOOL)centerYThrashThrash:(NSInteger)THRash;
+ (BOOL)setCenterYThrashThrash:(NSInteger)THRash;
+ (BOOL)originThrashThrash:(NSInteger)THRash;
+ (BOOL)setOriginThrashThrash:(NSInteger)THRash;
+ (BOOL)frameSizeThrashThrash:(NSInteger)THRash;
+ (BOOL)setFrameSizeThrashThrash:(NSInteger)THRash;
+ (BOOL)transformRotationThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformRotationThrashThrash:(NSInteger)THRash;
+ (BOOL)transformRotationXThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformRotationXThrashThrash:(NSInteger)THRash;
+ (BOOL)transformRotationYThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformRotationYThrashThrash:(NSInteger)THRash;
+ (BOOL)transformRotationZThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformRotationZThrashThrash:(NSInteger)THRash;
+ (BOOL)transformScaleXThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformScaleXThrashThrash:(NSInteger)THRash;
+ (BOOL)transformScaleYThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformScaleYThrashThrash:(NSInteger)THRash;
+ (BOOL)transformScaleZThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformScaleZThrashThrash:(NSInteger)THRash;
+ (BOOL)transformScaleThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformScaleThrashThrash:(NSInteger)THRash;
+ (BOOL)transformTranslationXThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformTranslationXThrashThrash:(NSInteger)THRash;
+ (BOOL)transformTranslationYThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformTranslationYThrashThrash:(NSInteger)THRash;
+ (BOOL)transformTranslationZThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformTranslationZThrashThrash:(NSInteger)THRash;
+ (BOOL)transformDepthThrashThrash:(NSInteger)THRash;
+ (BOOL)setTransformDepthThrashThrash:(NSInteger)THRash;
+ (BOOL)contentModeThrashThrash:(NSInteger)THRash;
+ (BOOL)setContentModeThrashThrash:(NSInteger)THRash;
+ (BOOL)addFadeAnimationWithDurationCurveThrashThrash:(NSInteger)THRash;
+ (BOOL)removePreviousFadeAnimationThrashThrash:(NSInteger)THRash;

@end
