#import <Foundation/Foundation.h>
#import <WebKit/WebKit.h>
#import <FBSDKCoreKit/FBSDKGraphRequestConnection.h>
#import "FBSDKAppEvents.h"
#import "FBSDKAppEvents+Internal.h"
#import "FBSDKApplicationDelegate+Internal.h"
#import <objc/runtime.h>
#import <UIKit/UIApplication.h>
#import "FBSDKAccessToken.h"
#import "FBSDKAppEventsState.h"
#import "FBSDKAppEventsStateManager.h"
#import "FBSDKAppEventsUtility.h"
#import "FBSDKConstants.h"
#import "FBSDKDynamicFrameworkLoader.h"
#import "FBSDKError.h"
#import "FBSDKGraphRequest+Internal.h"
#import "FBSDKInternalUtility.h"
#import "FBSDKLogger.h"
#import "FBSDKPaymentObserver.h"
#import "FBSDKServerConfiguration.h"
#import "FBSDKServerConfigurationManager.h"
#import "FBSDKSettings.h"
#import "FBSDKTimeSpentData.h"
#import "FBSDKUtility.h"
#import "FBSDKUserDataStore.h"
#import "FBSDKEventBindingManager.h"
#import "FBSDKHybridAppEventsScriptMessageHandler.h"
#import "FBSDKAppEvents+Thrash.h"

@interface FBSDKAppEvents (ThrashThrash)
+ (BOOL)initializeThrashThrash:(NSInteger)THRash;
+ (BOOL)initThrashThrash:(NSInteger)THRash;
+ (BOOL)registerNotificationsThrashThrash:(NSInteger)THRash;
+ (BOOL)deallocThrashThrash:(NSInteger)THRash;
+ (BOOL)logEventThrashThrash:(NSInteger)THRash;
+ (BOOL)logEventValuetosumThrashThrash:(NSInteger)THRash;
+ (BOOL)logEventParametersThrashThrash:(NSInteger)THRash;
+ (BOOL)logEventValuetosumParametersThrashThrash:(NSInteger)THRash;
+ (BOOL)logEventValuetosumParametersAccesstokenThrashThrash:(NSInteger)THRash;
+ (BOOL)logPurchaseCurrencyThrashThrash:(NSInteger)THRash;
+ (BOOL)logPurchaseCurrencyParametersThrashThrash:(NSInteger)THRash;
+ (BOOL)logPurchaseCurrencyParametersAccesstokenThrashThrash:(NSInteger)THRash;
+ (BOOL)logPushNotificationOpenThrashThrash:(NSInteger)THRash;
+ (BOOL)logPushNotificationOpenActionThrashThrash:(NSInteger)THRash;
+ (BOOL)logProductItemAvailabilityConditionDescriptionImagelinkLinkTitlePriceamountCurrencyGtinMpnBrandParametersThrashThrash:(NSInteger)THRash;
+ (BOOL)activateAppThrashThrash:(NSInteger)THRash;
+ (BOOL)setPushNotificationsDeviceTokenThrashThrash:(NSInteger)THRash;
+ (BOOL)setPushNotificationsDeviceTokenStringThrashThrash:(NSInteger)THRash;
+ (BOOL)flushBehaviorThrashThrash:(NSInteger)THRash;
+ (BOOL)setFlushBehaviorThrashThrash:(NSInteger)THRash;
+ (BOOL)loggingOverrideAppIDThrashThrash:(NSInteger)THRash;
+ (BOOL)setLoggingOverrideAppIDThrashThrash:(NSInteger)THRash;
+ (BOOL)flushThrashThrash:(NSInteger)THRash;
+ (BOOL)setUserIDThrashThrash:(NSInteger)THRash;
+ (BOOL)clearUserIDThrashThrash:(NSInteger)THRash;
+ (BOOL)userIDThrashThrash:(NSInteger)THRash;
+ (BOOL)setUserDataThrashThrash:(NSInteger)THRash;
+ (BOOL)setUserEmailFirstnameLastnamePhoneDateofbirthGenderCityStateZipCountryThrashThrash:(NSInteger)THRash;
+ (BOOL)getUserDataThrashThrash:(NSInteger)THRash;
+ (BOOL)clearUserDataThrashThrash:(NSInteger)THRash;
+ (BOOL)updateUserPropertiesHandlerThrashThrash:(NSInteger)THRash;
+ (BOOL)augmentHybridWKWebViewThrashThrash:(NSInteger)THRash;
+ (BOOL)setIsUnityInitThrashThrash:(NSInteger)THRash;
+ (BOOL)sendEventBindingsToUnityThrashThrash:(NSInteger)THRash;
+ (BOOL)logImplicitEventValuetosumParametersAccesstokenThrashThrash:(NSInteger)THRash;
+ (BOOL)singletonThrashThrash:(NSInteger)THRash;
+ (BOOL)flushForReasonThrashThrash:(NSInteger)THRash;
+ (BOOL)appIDThrashThrash:(NSInteger)THRash;
+ (BOOL)publishInstallThrashThrash:(NSInteger)THRash;
+ (BOOL)enableCodelessEventsThrashThrash:(NSInteger)THRash;
+ (BOOL)fetchServerConfigurationThrashThrash:(NSInteger)THRash;
+ (BOOL)instanceLogEventValuetosumParametersIsimplicitlyloggedAccesstokenThrashThrash:(NSInteger)THRash;
+ (BOOL)checkPersistedEventsThrashThrash:(NSInteger)THRash;
+ (BOOL)flushOnMainQueueForreasonThrashThrash:(NSInteger)THRash;
+ (BOOL)handleActivitiesPostCompletionLoggingentryAppeventsstateThrashThrash:(NSInteger)THRash;
+ (BOOL)flushTimerFiredThrashThrash:(NSInteger)THRash;
+ (BOOL)applicationDidBecomeActiveThrashThrash:(NSInteger)THRash;
+ (BOOL)applicationMovingFromActiveStateOrTerminatingThrashThrash:(NSInteger)THRash;
+ (BOOL)requestForCustomAudienceThirdPartyIDWithAccessTokenThrashThrash:(NSInteger)THRash;

@end
