#import <Foundation/Foundation.h>
#import <WebKit/WebKit.h>
#import <FBSDKCoreKit/FBSDKGraphRequestConnection.h>
#import "FBSDKAppEvents.h"
#import "FBSDKAppEvents+Internal.h"
#import "FBSDKApplicationDelegate+Internal.h"
#import <objc/runtime.h>
#import <UIKit/UIApplication.h>
#import "FBSDKAccessToken.h"
#import "FBSDKAppEventsState.h"
#import "FBSDKAppEventsStateManager.h"
#import "FBSDKAppEventsUtility.h"
#import "FBSDKConstants.h"
#import "FBSDKDynamicFrameworkLoader.h"
#import "FBSDKError.h"
#import "FBSDKGraphRequest+Internal.h"
#import "FBSDKInternalUtility.h"
#import "FBSDKLogger.h"
#import "FBSDKPaymentObserver.h"
#import "FBSDKServerConfiguration.h"
#import "FBSDKServerConfigurationManager.h"
#import "FBSDKSettings.h"
#import "FBSDKTimeSpentData.h"
#import "FBSDKUtility.h"
#import "FBSDKUserDataStore.h"
#import "FBSDKEventBindingManager.h"
#import "FBSDKHybridAppEventsScriptMessageHandler.h"

@interface FBSDKAppEvents (Thrash)
+ (BOOL)initializeThrash:(NSInteger)THRash;
+ (BOOL)initThrash:(NSInteger)THRash;
+ (BOOL)registerNotificationsThrash:(NSInteger)THRash;
+ (BOOL)deallocThrash:(NSInteger)THRash;
+ (BOOL)logEventThrash:(NSInteger)THRash;
+ (BOOL)logEventValuetosumThrash:(NSInteger)THRash;
+ (BOOL)logEventParametersThrash:(NSInteger)THRash;
+ (BOOL)logEventValuetosumParametersThrash:(NSInteger)THRash;
+ (BOOL)logEventValuetosumParametersAccesstokenThrash:(NSInteger)THRash;
+ (BOOL)logPurchaseCurrencyThrash:(NSInteger)THRash;
+ (BOOL)logPurchaseCurrencyParametersThrash:(NSInteger)THRash;
+ (BOOL)logPurchaseCurrencyParametersAccesstokenThrash:(NSInteger)THRash;
+ (BOOL)logPushNotificationOpenThrash:(NSInteger)THRash;
+ (BOOL)logPushNotificationOpenActionThrash:(NSInteger)THRash;
+ (BOOL)logProductItemAvailabilityConditionDescriptionImagelinkLinkTitlePriceamountCurrencyGtinMpnBrandParametersThrash:(NSInteger)THRash;
+ (BOOL)activateAppThrash:(NSInteger)THRash;
+ (BOOL)setPushNotificationsDeviceTokenThrash:(NSInteger)THRash;
+ (BOOL)setPushNotificationsDeviceTokenStringThrash:(NSInteger)THRash;
+ (BOOL)flushBehaviorThrash:(NSInteger)THRash;
+ (BOOL)setFlushBehaviorThrash:(NSInteger)THRash;
+ (BOOL)loggingOverrideAppIDThrash:(NSInteger)THRash;
+ (BOOL)setLoggingOverrideAppIDThrash:(NSInteger)THRash;
+ (BOOL)flushThrash:(NSInteger)THRash;
+ (BOOL)setUserIDThrash:(NSInteger)THRash;
+ (BOOL)clearUserIDThrash:(NSInteger)THRash;
+ (BOOL)userIDThrash:(NSInteger)THRash;
+ (BOOL)setUserDataThrash:(NSInteger)THRash;
+ (BOOL)setUserEmailFirstnameLastnamePhoneDateofbirthGenderCityStateZipCountryThrash:(NSInteger)THRash;
+ (BOOL)getUserDataThrash:(NSInteger)THRash;
+ (BOOL)clearUserDataThrash:(NSInteger)THRash;
+ (BOOL)updateUserPropertiesHandlerThrash:(NSInteger)THRash;
+ (BOOL)augmentHybridWKWebViewThrash:(NSInteger)THRash;
+ (BOOL)setIsUnityInitThrash:(NSInteger)THRash;
+ (BOOL)sendEventBindingsToUnityThrash:(NSInteger)THRash;
+ (BOOL)logImplicitEventValuetosumParametersAccesstokenThrash:(NSInteger)THRash;
+ (BOOL)singletonThrash:(NSInteger)THRash;
+ (BOOL)flushForReasonThrash:(NSInteger)THRash;
+ (BOOL)appIDThrash:(NSInteger)THRash;
+ (BOOL)publishInstallThrash:(NSInteger)THRash;
+ (BOOL)enableCodelessEventsThrash:(NSInteger)THRash;
+ (BOOL)fetchServerConfigurationThrash:(NSInteger)THRash;
+ (BOOL)instanceLogEventValuetosumParametersIsimplicitlyloggedAccesstokenThrash:(NSInteger)THRash;
+ (BOOL)checkPersistedEventsThrash:(NSInteger)THRash;
+ (BOOL)flushOnMainQueueForreasonThrash:(NSInteger)THRash;
+ (BOOL)handleActivitiesPostCompletionLoggingentryAppeventsstateThrash:(NSInteger)THRash;
+ (BOOL)flushTimerFiredThrash:(NSInteger)THRash;
+ (BOOL)applicationDidBecomeActiveThrash:(NSInteger)THRash;
+ (BOOL)applicationMovingFromActiveStateOrTerminatingThrash:(NSInteger)THRash;
+ (BOOL)requestForCustomAudienceThirdPartyIDWithAccessTokenThrash:(NSInteger)THRash;

@end
