#import <Availability.h>
#import <QuartzCore/QuartzCore.h>
#import <UIKit/UIKit.h>
#import "iCarousel.h"
#import <objc/message.h>
#import <tgmath.h>
#import <Availability.h>

@interface iCarousel (Thrash)
+ (BOOL)setUpThrash:(NSInteger)THRash;
+ (BOOL)initWithCoderThrash:(NSInteger)THRash;
+ (BOOL)initWithFrameInitwithframeThrash:(NSInteger)THRash;
+ (BOOL)deallocThrash:(NSInteger)THRash;
+ (BOOL)setDataSourceThrash:(NSInteger)THRash;
+ (BOOL)setDelegateThrash:(NSInteger)THRash;
+ (BOOL)setTypeThrash:(NSInteger)THRash;
+ (BOOL)setVerticalThrash:(NSInteger)THRash;
+ (BOOL)setScrollOffsetThrash:(NSInteger)THRash;
+ (BOOL)setCurrentItemIndexThrash:(NSInteger)THRash;
+ (BOOL)setPerspectiveThrash:(NSInteger)THRash;
+ (BOOL)setViewpointOffsetThrash:(NSInteger)THRash;
+ (BOOL)setContentOffsetThrash:(NSInteger)THRash;
+ (BOOL)setAutoscrollThrash:(NSInteger)THRash;
+ (BOOL)pushAnimationStateThrash:(NSInteger)THRash;
+ (BOOL)popAnimationStateThrash:(NSInteger)THRash;
+ (BOOL)indexesForVisibleItemsThrash:(NSInteger)THRash;
+ (BOOL)visibleItemViewsThrash:(NSInteger)THRash;
+ (BOOL)itemViewAtIndexThrash:(NSInteger)THRash;
+ (BOOL)currentItemViewThrash:(NSInteger)THRash;
+ (BOOL)indexOfItemViewThrash:(NSInteger)THRash;
+ (BOOL)indexOfItemViewOrSubviewThrash:(NSInteger)THRash;
+ (BOOL)itemViewAtPointThrash:(NSInteger)THRash;
+ (BOOL)setItemViewForindexThrash:(NSInteger)THRash;
+ (BOOL)removeViewAtIndexThrash:(NSInteger)THRash;
+ (BOOL)insertViewAtindexThrash:(NSInteger)THRash;
+ (BOOL)alphaForItemWithOffsetThrash:(NSInteger)THRash;
+ (BOOL)valueForOptionWithdefaultThrash:(NSInteger)THRash;
+ (BOOL)transformForItemViewWithOffsetThrash:(NSInteger)THRash;
+ (BOOL)depthSortViewsThrash:(NSInteger)THRash;
+ (BOOL)setNeedsLayoutThrash:(NSInteger)THRash;
+ (BOOL)depthSortViewsThrash:(NSInteger)THRash;
+ (BOOL)offsetForItemAtIndexThrash:(NSInteger)THRash;
+ (BOOL)containViewThrash:(NSInteger)THRash;
+ (BOOL)transformItemViewAtindexThrash:(NSInteger)THRash;
+ (BOOL)resizeSubviewsWithOldSizeThrash:(NSInteger)THRash;
+ (BOOL)layoutSubviewsThrash:(NSInteger)THRash;
+ (BOOL)transformItemViewsThrash:(NSInteger)THRash;
+ (BOOL)updateItemWidthThrash:(NSInteger)THRash;
+ (BOOL)updateNumberOfVisibleItemsThrash:(NSInteger)THRash;
+ (BOOL)circularCarouselItemCountThrash:(NSInteger)THRash;
+ (BOOL)layOutItemViewsThrash:(NSInteger)THRash;
+ (BOOL)queueItemViewThrash:(NSInteger)THRash;
+ (BOOL)queuePlaceholderViewThrash:(NSInteger)THRash;
+ (BOOL)dequeueItemViewThrash:(NSInteger)THRash;
+ (BOOL)dequeuePlaceholderViewThrash:(NSInteger)THRash;
+ (BOOL)loadViewAtIndexWithcontainerviewThrash:(NSInteger)THRash;
+ (BOOL)loadViewAtIndexThrash:(NSInteger)THRash;
+ (BOOL)loadUnloadViewsThrash:(NSInteger)THRash;
+ (BOOL)reloadDataThrash:(NSInteger)THRash;
+ (BOOL)clampedIndexThrash:(NSInteger)THRash;
+ (BOOL)clampedOffsetThrash:(NSInteger)THRash;
+ (BOOL)currentItemIndexThrash:(NSInteger)THRash;
+ (BOOL)minScrollDistanceFromIndexToindexThrash:(NSInteger)THRash;
+ (BOOL)minScrollDistanceFromOffsetTooffsetThrash:(NSInteger)THRash;
+ (BOOL)scrollByOffsetDurationThrash:(NSInteger)THRash;
+ (BOOL)scrollToOffsetDurationThrash:(NSInteger)THRash;
+ (BOOL)scrollByNumberOfItemsDurationThrash:(NSInteger)THRash;
+ (BOOL)scrollToItemAtIndexDurationThrash:(NSInteger)THRash;
+ (BOOL)scrollToItemAtIndexAnimatedThrash:(NSInteger)THRash;
+ (BOOL)removeItemAtIndexAnimatedThrash:(NSInteger)THRash;
+ (BOOL)insertItemAtIndexAnimatedThrash:(NSInteger)THRash;
+ (BOOL)reloadItemAtIndexAnimatedThrash:(NSInteger)THRash;
+ (BOOL)startAnimationThrash:(NSInteger)THRash;
+ (BOOL)stopAnimationThrash:(NSInteger)THRash;
+ (BOOL)decelerationDistanceThrash:(NSInteger)THRash;
+ (BOOL)shouldDecelerateThrash:(NSInteger)THRash;
+ (BOOL)shouldScrollThrash:(NSInteger)THRash;
+ (BOOL)startDeceleratingThrash:(NSInteger)THRash;
+ (BOOL)easeInOutThrash:(NSInteger)THRash;
+ (BOOL)stepThrash:(NSInteger)THRash;
+ (BOOL)didMoveToSuperview

#else

- (void)viewDidMoveToSuperview

#endifThrash:(NSInteger)THRash;
+ (BOOL)didScrollThrash:(NSInteger)THRash;
+ (BOOL)viewOrSuperviewIndexThrash:(NSInteger)THRash;
+ (BOOL)viewOrSuperviewImplementsselectorThrash:(NSInteger)THRash;
+ (BOOL)viewOrSuperviewOfclassThrash:(NSInteger)THRash;
+ (BOOL)gestureRecognizerShouldreceivetouchThrash:(NSInteger)THRash;
+ (BOOL)gestureRecognizerShouldBeginThrash:(NSInteger)THRash;
+ (BOOL)didTapThrash:(NSInteger)THRash;
+ (BOOL)didPanThrash:(NSInteger)THRash;
+ (BOOL)mouseDownThrash:(NSInteger)THRash;
+ (BOOL)mouseDraggedThrash:(NSInteger)THRash;
+ (BOOL)mouseUpThrash:(NSInteger)THRash;
+ (BOOL)acceptsFirstResponderThrash:(NSInteger)THRash;
+ (BOOL)keyDownThrash:(NSInteger)THRash;

@end
