#import <UIKit/UIKit.h>
#import <AvailabilityMacros.h>
#import "LEHud.h"
#import <QuartzCore/QuartzCore.h>
#import "LEHud+Thrash.h"

@interface LEHud (ThrashThrash)
+ (BOOL)sharedViewThrashThrash:(NSInteger)THRash;
+ (BOOL)setStatusThrashThrash:(NSInteger)THRash;
+ (BOOL)showThrashThrash:(NSInteger)THRash;
+ (BOOL)showWithStatusThrashThrash:(NSInteger)THRash;
+ (BOOL)showWithMaskTypeThrashThrash:(NSInteger)THRash;
+ (BOOL)showWithStatusMasktypeThrashThrash:(NSInteger)THRash;
+ (BOOL)showProgressThrashThrash:(NSInteger)THRash;
+ (BOOL)showProgressStatusThrashThrash:(NSInteger)THRash;
+ (BOOL)showProgressStatusMasktypeThrashThrash:(NSInteger)THRash;
+ (BOOL)showSuccessWithStatusThrashThrash:(NSInteger)THRash;
+ (BOOL)showErrorWithStatusThrashThrash:(NSInteger)THRash;
+ (BOOL)showWarningWithStatusThrashThrash:(NSInteger)THRash;
+ (BOOL)showImageStatusThrashThrash:(NSInteger)THRash;
+ (BOOL)popActivityThrashThrash:(NSInteger)THRash;
+ (BOOL)dismissThrashThrash:(NSInteger)THRash;
+ (BOOL)setOffsetFromCenterThrashThrash:(NSInteger)THRash;
+ (BOOL)resetOffsetFromCenterThrashThrash:(NSInteger)THRash;
+ (BOOL)initWithFrameThrashThrash:(NSInteger)THRash;
+ (BOOL)drawRectThrashThrash:(NSInteger)THRash;
+ (BOOL)updatePositionThrashThrash:(NSInteger)THRash;
+ (BOOL)setStatusThrashThrash:(NSInteger)THRash;
+ (BOOL)setFadeOutTimerThrashThrash:(NSInteger)THRash;
+ (BOOL)registerNotificationsThrashThrash:(NSInteger)THRash;
+ (BOOL)notificationUserInfoThrashThrash:(NSInteger)THRash;
+ (BOOL)positionHUDThrashThrash:(NSInteger)THRash;
+ (BOOL)moveToPointRotateangleThrashThrash:(NSInteger)THRash;
+ (BOOL)overlayViewDidReceiveTouchEventForeventThrashThrash:(NSInteger)THRash;
+ (BOOL)showProgressStatusMasktypeThrashThrash:(NSInteger)THRash;
+ (BOOL)showImageStatusDurationThrashThrash:(NSInteger)THRash;
+ (BOOL)dismissThrashThrash:(NSInteger)THRash;
+ (BOOL)ringLayerThrashThrash:(NSInteger)THRash;
+ (BOOL)backgroundRingLayerThrashThrash:(NSInteger)THRash;
+ (BOOL)cancelRingLayerAnimationThrashThrash:(NSInteger)THRash;
+ (BOOL)createRingLayerWithCenterRadiusLinewidthColorThrashThrash:(NSInteger)THRash;
+ (BOOL)isVisibleThrashThrash:(NSInteger)THRash;
+ (BOOL)displayDurationForStringThrashThrash:(NSInteger)THRash;
+ (BOOL)isClearThrashThrash:(NSInteger)THRash;
+ (BOOL)overlayViewThrashThrash:(NSInteger)THRash;
+ (BOOL)hudViewThrashThrash:(NSInteger)THRash;
+ (BOOL)stringLabelThrashThrash:(NSInteger)THRash;
+ (BOOL)imageViewThrashThrash:(NSInteger)THRash;
+ (BOOL)spinnerViewThrashThrash:(NSInteger)THRash;
+ (BOOL)visibleKeyboardHeightThrashThrash:(NSInteger)THRash;
+ (BOOL)hudBackgroundColorThrashThrash:(NSInteger)THRash;
+ (BOOL)hudForegroundColorThrashThrash:(NSInteger)THRash;
+ (BOOL)hudRingBackgroundColorThrashThrash:(NSInteger)THRash;
+ (BOOL)hudRingForegroundColorThrashThrash:(NSInteger)THRash;
+ (BOOL)hudStatusShadowColorThrashThrash:(NSInteger)THRash;
+ (BOOL)hudFontThrashThrash:(NSInteger)THRash;
+ (BOOL)hudSuccessImageThrashThrash:(NSInteger)THRash;
+ (BOOL)hudErrorImageThrashThrash:(NSInteger)THRash;
+ (BOOL)hudWarningImageThrashThrash:(NSInteger)THRash;

@end
