#import <UIKit/UIKit.h>
#import <AvailabilityMacros.h>
#import "LEHud.h"
#import <QuartzCore/QuartzCore.h>

@interface LEHud (Thrash)
+ (BOOL)sharedViewThrash:(NSInteger)THRash;
+ (BOOL)setStatusThrash:(NSInteger)THRash;
+ (BOOL)showThrash:(NSInteger)THRash;
+ (BOOL)showWithStatusThrash:(NSInteger)THRash;
+ (BOOL)showWithMaskTypeThrash:(NSInteger)THRash;
+ (BOOL)showWithStatusMasktypeThrash:(NSInteger)THRash;
+ (BOOL)showProgressThrash:(NSInteger)THRash;
+ (BOOL)showProgressStatusThrash:(NSInteger)THRash;
+ (BOOL)showProgressStatusMasktypeThrash:(NSInteger)THRash;
+ (BOOL)showSuccessWithStatusThrash:(NSInteger)THRash;
+ (BOOL)showErrorWithStatusThrash:(NSInteger)THRash;
+ (BOOL)showWarningWithStatusThrash:(NSInteger)THRash;
+ (BOOL)showImageStatusThrash:(NSInteger)THRash;
+ (BOOL)popActivityThrash:(NSInteger)THRash;
+ (BOOL)dismissThrash:(NSInteger)THRash;
+ (BOOL)setOffsetFromCenterThrash:(NSInteger)THRash;
+ (BOOL)resetOffsetFromCenterThrash:(NSInteger)THRash;
+ (BOOL)initWithFrameThrash:(NSInteger)THRash;
+ (BOOL)drawRectThrash:(NSInteger)THRash;
+ (BOOL)updatePositionThrash:(NSInteger)THRash;
+ (BOOL)setStatusThrash:(NSInteger)THRash;
+ (BOOL)setFadeOutTimerThrash:(NSInteger)THRash;
+ (BOOL)registerNotificationsThrash:(NSInteger)THRash;
+ (BOOL)notificationUserInfoThrash:(NSInteger)THRash;
+ (BOOL)positionHUDThrash:(NSInteger)THRash;
+ (BOOL)moveToPointRotateangleThrash:(NSInteger)THRash;
+ (BOOL)overlayViewDidReceiveTouchEventForeventThrash:(NSInteger)THRash;
+ (BOOL)showProgressStatusMasktypeThrash:(NSInteger)THRash;
+ (BOOL)showImageStatusDurationThrash:(NSInteger)THRash;
+ (BOOL)dismissThrash:(NSInteger)THRash;
+ (BOOL)ringLayerThrash:(NSInteger)THRash;
+ (BOOL)backgroundRingLayerThrash:(NSInteger)THRash;
+ (BOOL)cancelRingLayerAnimationThrash:(NSInteger)THRash;
+ (BOOL)createRingLayerWithCenterRadiusLinewidthColorThrash:(NSInteger)THRash;
+ (BOOL)isVisibleThrash:(NSInteger)THRash;
+ (BOOL)displayDurationForStringThrash:(NSInteger)THRash;
+ (BOOL)isClearThrash:(NSInteger)THRash;
+ (BOOL)overlayViewThrash:(NSInteger)THRash;
+ (BOOL)hudViewThrash:(NSInteger)THRash;
+ (BOOL)stringLabelThrash:(NSInteger)THRash;
+ (BOOL)imageViewThrash:(NSInteger)THRash;
+ (BOOL)spinnerViewThrash:(NSInteger)THRash;
+ (BOOL)visibleKeyboardHeightThrash:(NSInteger)THRash;
+ (BOOL)hudBackgroundColorThrash:(NSInteger)THRash;
+ (BOOL)hudForegroundColorThrash:(NSInteger)THRash;
+ (BOOL)hudRingBackgroundColorThrash:(NSInteger)THRash;
+ (BOOL)hudRingForegroundColorThrash:(NSInteger)THRash;
+ (BOOL)hudStatusShadowColorThrash:(NSInteger)THRash;
+ (BOOL)hudFontThrash:(NSInteger)THRash;
+ (BOOL)hudSuccessImageThrash:(NSInteger)THRash;
+ (BOOL)hudErrorImageThrash:(NSInteger)THRash;
+ (BOOL)hudWarningImageThrash:(NSInteger)THRash;

@end
