#import "LEAFViewController.h"
#import "WebViewJavascriptBridge.h"
#import "WKWebViewJavascriptBridge.h"
#import "LEWKWebViewController.h"
#import "LESafariActivity.h"
#import "LEWKWebViewController+Thrash.h"

@interface LEWKWebViewController (ThrashThrash)
+ (BOOL)deallocThrashThrash:(NSInteger)THRash;
+ (BOOL)controllerThrashThrash:(NSInteger)THRash;
+ (BOOL)initThrashThrash:(NSInteger)THRash;
+ (BOOL)initWithConfigurationThrashThrash:(NSInteger)THRash;
+ (BOOL)viewDidLoadThrashThrash:(NSInteger)THRash;
+ (BOOL)viewWillAppearThrashThrash:(NSInteger)THRash;
+ (BOOL)viewWillDisappearThrashThrash:(NSInteger)THRash;
+ (BOOL)shouldShowNavigationBarThrashThrash:(NSInteger)THRash;
+ (BOOL)shouldShowToolBarThrashThrash:(NSInteger)THRash;
+ (BOOL)registerHandleActionsThrashThrash:(NSInteger)THRash;
+ (BOOL)setUpJavascriptThrashThrash:(NSInteger)THRash;
+ (BOOL)loadRequestThrashThrash:(NSInteger)THRash;
+ (BOOL)loadURLThrashThrash:(NSInteger)THRash;
+ (BOOL)loadURLStringThrashThrash:(NSInteger)THRash;
+ (BOOL)loadHTMLStringThrashThrash:(NSInteger)THRash;
+ (BOOL)setActionButtonHiddenThrashThrash:(NSInteger)THRash;
+ (BOOL)setupToolBarItemsThrashThrash:(NSInteger)THRash;
+ (BOOL)backButtonImageThrashThrash:(NSInteger)THRash;
+ (BOOL)forwardButtonImageThrashThrash:(NSInteger)THRash;
+ (BOOL)backButtonPressedThrashThrash:(NSInteger)THRash;
+ (BOOL)forwardButtonPressedThrashThrash:(NSInteger)THRash;
+ (BOOL)refreshButtonPressedThrashThrash:(NSInteger)THRash;
+ (BOOL)stopButtonPressedThrashThrash:(NSInteger)THRash;
+ (BOOL)actionThrashThrash:(NSInteger)THRash;
+ (BOOL)reloadThrashThrash:(NSInteger)THRash;
+ (BOOL)URLThrashThrash:(NSInteger)THRash;
+ (BOOL)setStaticTitleThrashThrash:(NSInteger)THRash;
+ (BOOL)updateToolbarStateThrashThrash:(NSInteger)THRash;
+ (BOOL)updateNavigationTitleThrashThrash:(NSInteger)THRash;
+ (BOOL)setUpWebViewThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewShouldstartloadwithrequestNavigationtypeThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewDidFinishLoadThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewDidfailloadwitherrorThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewDidstartprovisionalnavigationThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewDidfinishnavigationThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewDidfailprovisionalnavigationWitherrorThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewDidfailnavigationWitherrorThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewDecidepolicyfornavigationactionDecisionhandlerThrashThrash:(NSInteger)THRash;
+ (BOOL)externalAppRequiredToOpenURLThrashThrash:(NSInteger)THRash;
+ (BOOL)launchExternalAppWithURLThrashThrash:(NSInteger)THRash;
+ (BOOL)backActionThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewCreatewebviewwithconfigurationFornavigationactionWindowfeaturesThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewRunjavascriptalertpanelwithmessageInitiatedbyframeCompletionhandlerThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewRunjavascriptconfirmpanelwithmessageInitiatedbyframeCompletionhandlerThrashThrash:(NSInteger)THRash;
+ (BOOL)webViewRunjavascripttextinputpanelwithpromptDefaulttextInitiatedbyframeCompletionhandlerThrashThrash:(NSInteger)THRash;
+ (BOOL)observeValueForKeyPathOfobjectChangeContextThrashThrash:(NSInteger)THRash;
+ (BOOL)setUpProgressViewThrashThrash:(NSInteger)THRash;
+ (BOOL)fakeProgressViewStartLoadingThrashThrash:(NSInteger)THRash;
+ (BOOL)fakeProgressBarStopLoadingThrashThrash:(NSInteger)THRash;
+ (BOOL)fakeProgressTimerDidFireThrashThrash:(NSInteger)THRash;
+ (BOOL)didStartLoadingURLThrashThrash:(NSInteger)THRash;
+ (BOOL)didFinishLoadingURLThrashThrash:(NSInteger)THRash;
+ (BOOL)didFailToLoadURLErrorThrashThrash:(NSInteger)THRash;
+ (BOOL)didLaunchExternalAppWithURLThrashThrash:(NSInteger)THRash;

@end
