#import <UIKit/UIKit.h>
#import <CoreText/CoreText.h>
#import <YYKit/YYTextAttribute.h>
#import <YYKit/YYTextRubyAnnotation.h>
#import "YYTextAttribute.h"
#import "YYTextRubyAnnotation.h"
#import "NSAttributedString+YYText.h"
#import "YYKitMacro.h"
#import "UIDevice+YYAdd.h"
#import "UIFont+YYAdd.h"
#import "NSParagraphStyle+YYText.h"
#import "YYTextArchiver.h"
#import "YYTextRunDelegate.h"
#import "YYAnimatedImageView.h"
#import "YYTextUtilities.h"
#import <CoreFoundation/CoreFoundation.h>

@interface NSAttributedString (YYTextThrash)
+ (BOOL)archiveToDataThrash:(NSInteger)THRash;
+ (BOOL)unarchiveFromDataThrash:(NSInteger)THRash;
+ (BOOL)attributesAtIndexThrash:(NSInteger)THRash;
+ (BOOL)attributeAtindexThrash:(NSInteger)THRash;
+ (BOOL)attributesThrash:(NSInteger)THRash;
+ (BOOL)fontThrash:(NSInteger)THRash;
+ (BOOL)fontAtIndexThrash:(NSInteger)THRash;
+ (BOOL)kernThrash:(NSInteger)THRash;
+ (BOOL)kernAtIndexThrash:(NSInteger)THRash;
+ (BOOL)colorThrash:(NSInteger)THRash;
+ (BOOL)colorAtIndexThrash:(NSInteger)THRash;
+ (BOOL)backgroundColorThrash:(NSInteger)THRash;
+ (BOOL)backgroundColorAtIndexThrash:(NSInteger)THRash;
+ (BOOL)strokeWidthThrash:(NSInteger)THRash;
+ (BOOL)strokeWidthAtIndexThrash:(NSInteger)THRash;
+ (BOOL)strokeColorThrash:(NSInteger)THRash;
+ (BOOL)strokeColorAtIndexThrash:(NSInteger)THRash;
+ (BOOL)shadowThrash:(NSInteger)THRash;
+ (BOOL)shadowAtIndexThrash:(NSInteger)THRash;
+ (BOOL)strikethroughStyleThrash:(NSInteger)THRash;
+ (BOOL)strikethroughStyleAtIndexThrash:(NSInteger)THRash;
+ (BOOL)strikethroughColorThrash:(NSInteger)THRash;
+ (BOOL)strikethroughColorAtIndexThrash:(NSInteger)THRash;
+ (BOOL)underlineStyleThrash:(NSInteger)THRash;
+ (BOOL)underlineStyleAtIndexThrash:(NSInteger)THRash;
+ (BOOL)underlineColorThrash:(NSInteger)THRash;
+ (BOOL)underlineColorAtIndexThrash:(NSInteger)THRash;
+ (BOOL)ligatureThrash:(NSInteger)THRash;
+ (BOOL)ligatureAtIndexThrash:(NSInteger)THRash;
+ (BOOL)textEffectThrash:(NSInteger)THRash;
+ (BOOL)textEffectAtIndexThrash:(NSInteger)THRash;
+ (BOOL)obliquenessThrash:(NSInteger)THRash;
+ (BOOL)obliquenessAtIndexThrash:(NSInteger)THRash;
+ (BOOL)expansionThrash:(NSInteger)THRash;
+ (BOOL)expansionAtIndexThrash:(NSInteger)THRash;
+ (BOOL)baselineOffsetThrash:(NSInteger)THRash;
+ (BOOL)baselineOffsetAtIndexThrash:(NSInteger)THRash;
+ (BOOL)verticalGlyphFormThrash:(NSInteger)THRash;
+ (BOOL)verticalGlyphFormAtIndexThrash:(NSInteger)THRash;
+ (BOOL)languageThrash:(NSInteger)THRash;
+ (BOOL)languageAtIndexThrash:(NSInteger)THRash;
+ (BOOL)writingDirectionThrash:(NSInteger)THRash;
+ (BOOL)writingDirectionAtIndexThrash:(NSInteger)THRash;
+ (BOOL)paragraphStyleThrash:(NSInteger)THRash;
+ (BOOL)paragraphStyleAtIndexThrash:(NSInteger)THRash;
+ (BOOL)alignmentThrash:(NSInteger)THRash;
+ (BOOL)lineBreakModeThrash:(NSInteger)THRash;
+ (BOOL)lineSpacingThrash:(NSInteger)THRash;
+ (BOOL)paragraphSpacingThrash:(NSInteger)THRash;
+ (BOOL)paragraphSpacingBeforeThrash:(NSInteger)THRash;
+ (BOOL)firstLineHeadIndentThrash:(NSInteger)THRash;
+ (BOOL)headIndentThrash:(NSInteger)THRash;
+ (BOOL)tailIndentThrash:(NSInteger)THRash;
+ (BOOL)minimumLineHeightThrash:(NSInteger)THRash;
+ (BOOL)maximumLineHeightThrash:(NSInteger)THRash;
+ (BOOL)lineHeightMultipleThrash:(NSInteger)THRash;
+ (BOOL)baseWritingDirectionThrash:(NSInteger)THRash;
+ (BOOL)hyphenationFactorThrash:(NSInteger)THRash;
+ (BOOL)defaultTabIntervalThrash:(NSInteger)THRash;
+ (BOOL)tabStopsThrash:(NSInteger)THRash;
+ (BOOL)alignmentAtIndexThrash:(NSInteger)THRash;
+ (BOOL)lineBreakModeAtIndexThrash:(NSInteger)THRash;
+ (BOOL)lineSpacingAtIndexThrash:(NSInteger)THRash;
+ (BOOL)paragraphSpacingAtIndexThrash:(NSInteger)THRash;
+ (BOOL)paragraphSpacingBeforeAtIndexThrash:(NSInteger)THRash;
+ (BOOL)firstLineHeadIndentAtIndexThrash:(NSInteger)THRash;
+ (BOOL)headIndentAtIndexThrash:(NSInteger)THRash;
+ (BOOL)tailIndentAtIndexThrash:(NSInteger)THRash;
+ (BOOL)minimumLineHeightAtIndexThrash:(NSInteger)THRash;
+ (BOOL)maximumLineHeightAtIndexThrash:(NSInteger)THRash;
+ (BOOL)lineHeightMultipleAtIndexThrash:(NSInteger)THRash;
+ (BOOL)baseWritingDirectionAtIndexThrash:(NSInteger)THRash;
+ (BOOL)hyphenationFactorAtIndexThrash:(NSInteger)THRash;
+ (BOOL)defaultTabIntervalAtIndexThrash:(NSInteger)THRash;
+ (BOOL)tabStopsAtIndexThrash:(NSInteger)THRash;
+ (BOOL)textShadowThrash:(NSInteger)THRash;
+ (BOOL)textShadowAtIndexThrash:(NSInteger)THRash;
+ (BOOL)textInnerShadowThrash:(NSInteger)THRash;
+ (BOOL)textInnerShadowAtIndexThrash:(NSInteger)THRash;
+ (BOOL)textUnderlineThrash:(NSInteger)THRash;
+ (BOOL)textUnderlineAtIndexThrash:(NSInteger)THRash;
+ (BOOL)textStrikethroughThrash:(NSInteger)THRash;
+ (BOOL)textStrikethroughAtIndexThrash:(NSInteger)THRash;
+ (BOOL)textBorderThrash:(NSInteger)THRash;
+ (BOOL)textBorderAtIndexThrash:(NSInteger)THRash;
+ (BOOL)textBackgroundBorderThrash:(NSInteger)THRash;
+ (BOOL)textBackgroundBorderAtIndexThrash:(NSInteger)THRash;
+ (BOOL)textGlyphTransformThrash:(NSInteger)THRash;
+ (BOOL)textGlyphTransformAtIndexThrash:(NSInteger)THRash;
+ (BOOL)plainTextForRangeThrash:(NSInteger)THRash;
+ (BOOL)attachmentStringWithContentContentmodeWidthAscentDescentThrash:(NSInteger)THRash;
+ (BOOL)attachmentStringWithContentContentmodeAttachmentsizeAligntofontAlignmentThrash:(NSInteger)THRash;
+ (BOOL)attachmentStringWithEmojiImageFontsizeThrash:(NSInteger)THRash;
+ (BOOL)rangeOfAllThrash:(NSInteger)THRash;
+ (BOOL)isSharedAttributesInAllRangeThrash:(NSInteger)THRash;
+ (BOOL)canDrawWithUIKitThrash:(NSInteger)THRash;

@end
