#import <UIKit/UIKit.h>
#import <CoreText/CoreText.h>
#import <YYKit/YYTextAttribute.h>
#import <YYKit/YYTextRubyAnnotation.h>
#import "YYTextAttribute.h"
#import "YYTextRubyAnnotation.h"
#import "NSAttributedString+YYText.h"
#import "YYKitMacro.h"
#import "UIDevice+YYAdd.h"
#import "UIFont+YYAdd.h"
#import "NSParagraphStyle+YYText.h"
#import "YYTextArchiver.h"
#import "YYTextRunDelegate.h"
#import "YYAnimatedImageView.h"
#import "YYTextUtilities.h"
#import <CoreFoundation/CoreFoundation.h>
#import "NSMutableAttributedString+YYTextThrash.h"

@interface NSMutableAttributedString (YYTextThrashThrash)
+ (BOOL)setAttributesThrashThrash:(NSInteger)THRash;
+ (BOOL)setAttributeValueThrashThrash:(NSInteger)THRash;
+ (BOOL)setAttributeValueRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)removeAttributesInRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setFontThrashThrash:(NSInteger)THRash;
+ (BOOL)setKernThrashThrash:(NSInteger)THRash;
+ (BOOL)setColorThrashThrash:(NSInteger)THRash;
+ (BOOL)setBackgroundColorThrashThrash:(NSInteger)THRash;
+ (BOOL)setStrokeWidthThrashThrash:(NSInteger)THRash;
+ (BOOL)setStrokeColorThrashThrash:(NSInteger)THRash;
+ (BOOL)setShadowThrashThrash:(NSInteger)THRash;
+ (BOOL)setStrikethroughStyleThrashThrash:(NSInteger)THRash;
+ (BOOL)setStrikethroughColorThrashThrash:(NSInteger)THRash;
+ (BOOL)setUnderlineStyleThrashThrash:(NSInteger)THRash;
+ (BOOL)setUnderlineColorThrashThrash:(NSInteger)THRash;
+ (BOOL)setLigatureThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextEffectThrashThrash:(NSInteger)THRash;
+ (BOOL)setObliquenessThrashThrash:(NSInteger)THRash;
+ (BOOL)setExpansionThrashThrash:(NSInteger)THRash;
+ (BOOL)setBaselineOffsetThrashThrash:(NSInteger)THRash;
+ (BOOL)setVerticalGlyphFormThrashThrash:(NSInteger)THRash;
+ (BOOL)setLanguageThrashThrash:(NSInteger)THRash;
+ (BOOL)setWritingDirectionThrashThrash:(NSInteger)THRash;
+ (BOOL)setParagraphStyleThrashThrash:(NSInteger)THRash;
+ (BOOL)setAlignmentThrashThrash:(NSInteger)THRash;
+ (BOOL)setBaseWritingDirectionThrashThrash:(NSInteger)THRash;
+ (BOOL)setLineSpacingThrashThrash:(NSInteger)THRash;
+ (BOOL)setParagraphSpacingThrashThrash:(NSInteger)THRash;
+ (BOOL)setParagraphSpacingBeforeThrashThrash:(NSInteger)THRash;
+ (BOOL)setFirstLineHeadIndentThrashThrash:(NSInteger)THRash;
+ (BOOL)setHeadIndentThrashThrash:(NSInteger)THRash;
+ (BOOL)setTailIndentThrashThrash:(NSInteger)THRash;
+ (BOOL)setLineBreakModeThrashThrash:(NSInteger)THRash;
+ (BOOL)setMinimumLineHeightThrashThrash:(NSInteger)THRash;
+ (BOOL)setMaximumLineHeightThrashThrash:(NSInteger)THRash;
+ (BOOL)setLineHeightMultipleThrashThrash:(NSInteger)THRash;
+ (BOOL)setHyphenationFactorThrashThrash:(NSInteger)THRash;
+ (BOOL)setDefaultTabIntervalThrashThrash:(NSInteger)THRash;
+ (BOOL)setTabStopsThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextShadowThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextInnerShadowThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextUnderlineThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextStrikethroughThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextBorderThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextBackgroundBorderThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextGlyphTransformThrashThrash:(NSInteger)THRash;
+ (BOOL)setFontRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setKernRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setColorRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setBackgroundColorRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setStrokeWidthRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setStrokeColorRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setShadowRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setStrikethroughStyleRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setStrikethroughColorRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setUnderlineStyleRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setUnderlineColorRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setLigatureRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextEffectRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setObliquenessRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setExpansionRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setBaselineOffsetRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setVerticalGlyphFormRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setLanguageRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setWritingDirectionRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setParagraphStyleRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setAlignmentRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setBaseWritingDirectionRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setLineSpacingRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setParagraphSpacingRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setParagraphSpacingBeforeRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setFirstLineHeadIndentRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setHeadIndentRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTailIndentRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setLineBreakModeRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setMinimumLineHeightRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setMaximumLineHeightRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setLineHeightMultipleRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setHyphenationFactorRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setDefaultTabIntervalRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTabStopsRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setSuperscriptRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setGlyphInfoRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setCharacterShapeRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setRunDelegateRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setBaselineClassRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setBaselineInfoRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setBaselineReferenceInfoRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setRubyAnnotationRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setAttachmentRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setLinkRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextBackedStringRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextBindingRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextShadowRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextInnerShadowRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextUnderlineRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextStrikethroughRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextBorderRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextBackgroundBorderRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextAttachmentRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextHighlightRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextBlockBorderRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextRubyAnnotationRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextGlyphTransformRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextHighlightRangeColorBackgroundcolorUserinfoTapactionLongpressactionThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextHighlightRangeColorBackgroundcolorTapactionThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextHighlightRangeColorBackgroundcolorUserinfoThrashThrash:(NSInteger)THRash;
+ (BOOL)insertStringAtindexThrashThrash:(NSInteger)THRash;
+ (BOOL)appendStringThrashThrash:(NSInteger)THRash;
+ (BOOL)setClearColorToJoinedEmojiThrashThrash:(NSInteger)THRash;
+ (BOOL)removeDiscontinuousAttributesInRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)allDiscontinuousAttributeKeysThrashThrash:(NSInteger)THRash;

@end
