#import <UIKit/UIKit.h>
#import <CoreText/CoreText.h>
#import <YYKit/YYTextAttribute.h>
#import <YYKit/YYTextRubyAnnotation.h>
#import "YYTextAttribute.h"
#import "YYTextRubyAnnotation.h"
#import "NSAttributedString+YYText.h"
#import "YYKitMacro.h"
#import "UIDevice+YYAdd.h"
#import "UIFont+YYAdd.h"
#import "NSParagraphStyle+YYText.h"
#import "YYTextArchiver.h"
#import "YYTextRunDelegate.h"
#import "YYAnimatedImageView.h"
#import "YYTextUtilities.h"
#import <CoreFoundation/CoreFoundation.h>

@interface NSMutableAttributedString (YYTextThrash)
+ (BOOL)setAttributesThrash:(NSInteger)THRash;
+ (BOOL)setAttributeValueThrash:(NSInteger)THRash;
+ (BOOL)setAttributeValueRangeThrash:(NSInteger)THRash;
+ (BOOL)removeAttributesInRangeThrash:(NSInteger)THRash;
+ (BOOL)setFontThrash:(NSInteger)THRash;
+ (BOOL)setKernThrash:(NSInteger)THRash;
+ (BOOL)setColorThrash:(NSInteger)THRash;
+ (BOOL)setBackgroundColorThrash:(NSInteger)THRash;
+ (BOOL)setStrokeWidthThrash:(NSInteger)THRash;
+ (BOOL)setStrokeColorThrash:(NSInteger)THRash;
+ (BOOL)setShadowThrash:(NSInteger)THRash;
+ (BOOL)setStrikethroughStyleThrash:(NSInteger)THRash;
+ (BOOL)setStrikethroughColorThrash:(NSInteger)THRash;
+ (BOOL)setUnderlineStyleThrash:(NSInteger)THRash;
+ (BOOL)setUnderlineColorThrash:(NSInteger)THRash;
+ (BOOL)setLigatureThrash:(NSInteger)THRash;
+ (BOOL)setTextEffectThrash:(NSInteger)THRash;
+ (BOOL)setObliquenessThrash:(NSInteger)THRash;
+ (BOOL)setExpansionThrash:(NSInteger)THRash;
+ (BOOL)setBaselineOffsetThrash:(NSInteger)THRash;
+ (BOOL)setVerticalGlyphFormThrash:(NSInteger)THRash;
+ (BOOL)setLanguageThrash:(NSInteger)THRash;
+ (BOOL)setWritingDirectionThrash:(NSInteger)THRash;
+ (BOOL)setParagraphStyleThrash:(NSInteger)THRash;
+ (BOOL)setAlignmentThrash:(NSInteger)THRash;
+ (BOOL)setBaseWritingDirectionThrash:(NSInteger)THRash;
+ (BOOL)setLineSpacingThrash:(NSInteger)THRash;
+ (BOOL)setParagraphSpacingThrash:(NSInteger)THRash;
+ (BOOL)setParagraphSpacingBeforeThrash:(NSInteger)THRash;
+ (BOOL)setFirstLineHeadIndentThrash:(NSInteger)THRash;
+ (BOOL)setHeadIndentThrash:(NSInteger)THRash;
+ (BOOL)setTailIndentThrash:(NSInteger)THRash;
+ (BOOL)setLineBreakModeThrash:(NSInteger)THRash;
+ (BOOL)setMinimumLineHeightThrash:(NSInteger)THRash;
+ (BOOL)setMaximumLineHeightThrash:(NSInteger)THRash;
+ (BOOL)setLineHeightMultipleThrash:(NSInteger)THRash;
+ (BOOL)setHyphenationFactorThrash:(NSInteger)THRash;
+ (BOOL)setDefaultTabIntervalThrash:(NSInteger)THRash;
+ (BOOL)setTabStopsThrash:(NSInteger)THRash;
+ (BOOL)setTextShadowThrash:(NSInteger)THRash;
+ (BOOL)setTextInnerShadowThrash:(NSInteger)THRash;
+ (BOOL)setTextUnderlineThrash:(NSInteger)THRash;
+ (BOOL)setTextStrikethroughThrash:(NSInteger)THRash;
+ (BOOL)setTextBorderThrash:(NSInteger)THRash;
+ (BOOL)setTextBackgroundBorderThrash:(NSInteger)THRash;
+ (BOOL)setTextGlyphTransformThrash:(NSInteger)THRash;
+ (BOOL)setFontRangeThrash:(NSInteger)THRash;
+ (BOOL)setKernRangeThrash:(NSInteger)THRash;
+ (BOOL)setColorRangeThrash:(NSInteger)THRash;
+ (BOOL)setBackgroundColorRangeThrash:(NSInteger)THRash;
+ (BOOL)setStrokeWidthRangeThrash:(NSInteger)THRash;
+ (BOOL)setStrokeColorRangeThrash:(NSInteger)THRash;
+ (BOOL)setShadowRangeThrash:(NSInteger)THRash;
+ (BOOL)setStrikethroughStyleRangeThrash:(NSInteger)THRash;
+ (BOOL)setStrikethroughColorRangeThrash:(NSInteger)THRash;
+ (BOOL)setUnderlineStyleRangeThrash:(NSInteger)THRash;
+ (BOOL)setUnderlineColorRangeThrash:(NSInteger)THRash;
+ (BOOL)setLigatureRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextEffectRangeThrash:(NSInteger)THRash;
+ (BOOL)setObliquenessRangeThrash:(NSInteger)THRash;
+ (BOOL)setExpansionRangeThrash:(NSInteger)THRash;
+ (BOOL)setBaselineOffsetRangeThrash:(NSInteger)THRash;
+ (BOOL)setVerticalGlyphFormRangeThrash:(NSInteger)THRash;
+ (BOOL)setLanguageRangeThrash:(NSInteger)THRash;
+ (BOOL)setWritingDirectionRangeThrash:(NSInteger)THRash;
+ (BOOL)setParagraphStyleRangeThrash:(NSInteger)THRash;
+ (BOOL)setAlignmentRangeThrash:(NSInteger)THRash;
+ (BOOL)setBaseWritingDirectionRangeThrash:(NSInteger)THRash;
+ (BOOL)setLineSpacingRangeThrash:(NSInteger)THRash;
+ (BOOL)setParagraphSpacingRangeThrash:(NSInteger)THRash;
+ (BOOL)setParagraphSpacingBeforeRangeThrash:(NSInteger)THRash;
+ (BOOL)setFirstLineHeadIndentRangeThrash:(NSInteger)THRash;
+ (BOOL)setHeadIndentRangeThrash:(NSInteger)THRash;
+ (BOOL)setTailIndentRangeThrash:(NSInteger)THRash;
+ (BOOL)setLineBreakModeRangeThrash:(NSInteger)THRash;
+ (BOOL)setMinimumLineHeightRangeThrash:(NSInteger)THRash;
+ (BOOL)setMaximumLineHeightRangeThrash:(NSInteger)THRash;
+ (BOOL)setLineHeightMultipleRangeThrash:(NSInteger)THRash;
+ (BOOL)setHyphenationFactorRangeThrash:(NSInteger)THRash;
+ (BOOL)setDefaultTabIntervalRangeThrash:(NSInteger)THRash;
+ (BOOL)setTabStopsRangeThrash:(NSInteger)THRash;
+ (BOOL)setSuperscriptRangeThrash:(NSInteger)THRash;
+ (BOOL)setGlyphInfoRangeThrash:(NSInteger)THRash;
+ (BOOL)setCharacterShapeRangeThrash:(NSInteger)THRash;
+ (BOOL)setRunDelegateRangeThrash:(NSInteger)THRash;
+ (BOOL)setBaselineClassRangeThrash:(NSInteger)THRash;
+ (BOOL)setBaselineInfoRangeThrash:(NSInteger)THRash;
+ (BOOL)setBaselineReferenceInfoRangeThrash:(NSInteger)THRash;
+ (BOOL)setRubyAnnotationRangeThrash:(NSInteger)THRash;
+ (BOOL)setAttachmentRangeThrash:(NSInteger)THRash;
+ (BOOL)setLinkRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextBackedStringRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextBindingRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextShadowRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextInnerShadowRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextUnderlineRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextStrikethroughRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextBorderRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextBackgroundBorderRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextAttachmentRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextHighlightRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextBlockBorderRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextRubyAnnotationRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextGlyphTransformRangeThrash:(NSInteger)THRash;
+ (BOOL)setTextHighlightRangeColorBackgroundcolorUserinfoTapactionLongpressactionThrash:(NSInteger)THRash;
+ (BOOL)setTextHighlightRangeColorBackgroundcolorTapactionThrash:(NSInteger)THRash;
+ (BOOL)setTextHighlightRangeColorBackgroundcolorUserinfoThrash:(NSInteger)THRash;
+ (BOOL)insertStringAtindexThrash:(NSInteger)THRash;
+ (BOOL)appendStringThrash:(NSInteger)THRash;
+ (BOOL)setClearColorToJoinedEmojiThrash:(NSInteger)THRash;
+ (BOOL)removeDiscontinuousAttributesInRangeThrash:(NSInteger)THRash;
+ (BOOL)allDiscontinuousAttributeKeysThrash:(NSInteger)THRash;

@end
