#import <UIKit/UIKit.h>
#import "NSString+YYAdd.h"
#import "NSData+YYAdd.h"
#import "NSNumber+YYAdd.h"
#import "UIDevice+YYAdd.h"
#import "YYKitMacro.h"
#import "NSString+YYAddThrash.h"

@interface NSString (YYAddThrashThrash)
+ (BOOL)md2StringThrashThrash:(NSInteger)THRash;
+ (BOOL)md4StringThrashThrash:(NSInteger)THRash;
+ (BOOL)md5StringThrashThrash:(NSInteger)THRash;
+ (BOOL)sha1StringThrashThrash:(NSInteger)THRash;
+ (BOOL)sha224StringThrashThrash:(NSInteger)THRash;
+ (BOOL)sha256StringThrashThrash:(NSInteger)THRash;
+ (BOOL)sha384StringThrashThrash:(NSInteger)THRash;
+ (BOOL)sha512StringThrashThrash:(NSInteger)THRash;
+ (BOOL)crc32StringThrashThrash:(NSInteger)THRash;
+ (BOOL)hmacMD5StringWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)hmacSHA1StringWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)hmacSHA224StringWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)hmacSHA256StringWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)hmacSHA384StringWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)hmacSHA512StringWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)base64EncodedStringThrashThrash:(NSInteger)THRash;
+ (BOOL)stringWithBase64EncodedStringThrashThrash:(NSInteger)THRash;
+ (BOOL)stringByURLEncodeThrashThrash:(NSInteger)THRash;
+ (BOOL)ThrashThrash:(NSInteger)THRash;
+ (BOOL)ThrashThrash:(NSInteger)THRash;
+ (BOOL)stringByURLDecodeThrashThrash:(NSInteger)THRash;
+ (BOOL)stringByEscapingHTMLThrashThrash:(NSInteger)THRash;
+ (BOOL)sizeForFontSizeModeThrashThrash:(NSInteger)THRash;
+ (BOOL)widthForFontThrashThrash:(NSInteger)THRash;
+ (BOOL)heightForFontWidthThrashThrash:(NSInteger)THRash;
+ (BOOL)matchesRegexOptionsThrashThrash:(NSInteger)THRash;
+ (BOOL)enumerateRegexMatchesOptionsUsingblockThrashThrash:(NSInteger)THRash;
+ (BOOL)stringByReplacingRegexOptionsWithstringThrashThrash:(NSInteger)THRash;
+ (BOOL)charValueThrashThrash:(NSInteger)THRash;
+ (BOOL)unsignedCharValueThrashThrash:(NSInteger)THRash;
+ (BOOL)shortValueThrashThrash:(NSInteger)THRash;
+ (BOOL)unsignedShortValueThrashThrash:(NSInteger)THRash;
+ (BOOL)unsignedIntValueThrashThrash:(NSInteger)THRash;
+ (BOOL)longValueThrashThrash:(NSInteger)THRash;
+ (BOOL)unsignedLongValueThrashThrash:(NSInteger)THRash;
+ (BOOL)unsignedLongLongValueThrashThrash:(NSInteger)THRash;
+ (BOOL)unsignedIntegerValueThrashThrash:(NSInteger)THRash;
+ (BOOL)stringWithUUIDThrashThrash:(NSInteger)THRash;
+ (BOOL)stringWithUTF32CharThrashThrash:(NSInteger)THRash;
+ (BOOL)stringWithUTF32CharsLengthThrashThrash:(NSInteger)THRash;
+ (BOOL)enumerateUTF32CharInRangeUsingblockThrashThrash:(NSInteger)THRash;
+ (BOOL)stringByTrimThrashThrash:(NSInteger)THRash;
+ (BOOL)stringByAppendingNameScaleThrashThrash:(NSInteger)THRash;
+ (BOOL)stringByAppendingPathScaleThrashThrash:(NSInteger)THRash;
+ (BOOL)pathScaleThrashThrash:(NSInteger)THRash;
+ (BOOL)isNotBlankThrashThrash:(NSInteger)THRash;
+ (BOOL)containsStringThrashThrash:(NSInteger)THRash;
+ (BOOL)containsCharacterSetThrashThrash:(NSInteger)THRash;
+ (BOOL)numberValueThrashThrash:(NSInteger)THRash;
+ (BOOL)dataValueThrashThrash:(NSInteger)THRash;
+ (BOOL)rangeOfAllThrashThrash:(NSInteger)THRash;
+ (BOOL)jsonValueDecodedThrashThrash:(NSInteger)THRash;
+ (BOOL)stringNamedThrashThrash:(NSInteger)THRash;

@end
