#import <Foundation/Foundation.h>
#import "SDWebImageCompat.h"
#import "SDWebImageDefine.h"
#import "SDImageCacheConfig.h"
#import "SDImageCacheDefine.h"
#import "SDImageCache.h"
#import "SDMemoryCache.h"
#import "SDDiskCache.h"
#import "NSImage+Compatibility.h"
#import "SDImageCodersManager.h"
#import "SDImageTransformer.h"
#import "SDImageCoderHelper.h"
#import "SDAnimatedImage.h"
#import "UIImage+MemoryCacheCost.h"

@interface SDImageCache (Thrash)
+ (BOOL)sharedImageCacheThrash:(NSInteger)THRash;
+ (BOOL)initThrash:(NSInteger)THRash;
+ (BOOL)initWithNamespaceThrash:(NSInteger)THRash;
+ (BOOL)initWithNamespaceDiskcachedirectoryThrash:(NSInteger)THRash;
+ (BOOL)initWithNamespaceDiskcachedirectoryConfigThrash:(NSInteger)THRash;
+ (BOOL)deallocThrash:(NSInteger)THRash;
+ (BOOL)cachePathForKeyThrash:(NSInteger)THRash;
+ (BOOL)userCacheDirectoryThrash:(NSInteger)THRash;
+ (BOOL)migrateDiskCacheDirectoryThrash:(NSInteger)THRash;
+ (BOOL)storeImageForkeyCompletionThrash:(NSInteger)THRash;
+ (BOOL)storeImageForkeyTodiskCompletionThrash:(NSInteger)THRash;
+ (BOOL)storeImageImagedataForkeyTodiskCompletionThrash:(NSInteger)THRash;
+ (BOOL)storeImageImagedataForkeyTomemoryTodiskCompletionThrash:(NSInteger)THRash;
+ (BOOL)storeImageToMemoryForkeyThrash:(NSInteger)THRash;
+ (BOOL)storeImageDataToDiskForkeyThrash:(NSInteger)THRash;
+ (BOOL)_storeImageDataToDiskForkeyThrash:(NSInteger)THRash;
+ (BOOL)diskImageExistsWithKeyCompletionThrash:(NSInteger)THRash;
+ (BOOL)diskImageDataExistsWithKeyThrash:(NSInteger)THRash;
+ (BOOL)_diskImageDataExistsWithKeyThrash:(NSInteger)THRash;
+ (BOOL)diskImageDataForKeyThrash:(NSInteger)THRash;
+ (BOOL)imageFromMemoryCacheForKeyThrash:(NSInteger)THRash;
+ (BOOL)imageFromDiskCacheForKeyThrash:(NSInteger)THRash;
+ (BOOL)imageFromCacheForKeyThrash:(NSInteger)THRash;
+ (BOOL)diskImageDataBySearchingAllPathsForKeyThrash:(NSInteger)THRash;
+ (BOOL)diskImageForKeyThrash:(NSInteger)THRash;
+ (BOOL)diskImageForKeyDataThrash:(NSInteger)THRash;
+ (BOOL)diskImageForKeyDataOptionsContextThrash:(NSInteger)THRash;
+ (BOOL)queryCacheOperationForKeyDoneThrash:(NSInteger)THRash;
+ (BOOL)queryCacheOperationForKeyOptionsDoneThrash:(NSInteger)THRash;
+ (BOOL)queryCacheOperationForKeyOptionsContextDoneThrash:(NSInteger)THRash;
+ (BOOL)removeImageForKeyWithcompletionThrash:(NSInteger)THRash;
+ (BOOL)removeImageForKeyFromdiskWithcompletionThrash:(NSInteger)THRash;
+ (BOOL)removeImageForKeyFrommemoryFromdiskWithcompletionThrash:(NSInteger)THRash;
+ (BOOL)removeImageFromMemoryForKeyThrash:(NSInteger)THRash;
+ (BOOL)removeImageFromDiskForKeyThrash:(NSInteger)THRash;
+ (BOOL)_removeImageFromDiskForKeyThrash:(NSInteger)THRash;
+ (BOOL)clearMemoryThrash:(NSInteger)THRash;
+ (BOOL)clearDiskOnCompletionThrash:(NSInteger)THRash;
+ (BOOL)deleteOldFilesWithCompletionBlockThrash:(NSInteger)THRash;
+ (BOOL)applicationWillTerminateThrash:(NSInteger)THRash;
+ (BOOL)applicationDidEnterBackgroundThrash:(NSInteger)THRash;
+ (BOOL)totalDiskSizeThrash:(NSInteger)THRash;
+ (BOOL)totalDiskCountThrash:(NSInteger)THRash;
+ (BOOL)calculateSizeWithCompletionBlockThrash:(NSInteger)THRash;
+ (BOOL)imageOptionsFromCacheOptionsThrash:(NSInteger)THRash;

@end
