#import <Foundation/Foundation.h>
#import "THRashCALayerN.h"

@interface THRashCALayerN (Thrash)
+ (BOOL)lsnapshotImageThrash:(NSInteger)THRash;
+ (BOOL)asnapshotPDFThrash:(NSInteger)THRash;
+ (BOOL)LSetlayershadowXOffsetMRadiusThrash:(NSInteger)THRash;
+ (BOOL)bremoveAllSublayersThrash:(NSInteger)THRash;
+ (BOOL)OleftThrash:(NSInteger)THRash;
+ (BOOL)dSetleftThrash:(NSInteger)THRash;
+ (BOOL)itopThrash:(NSInteger)THRash;
+ (BOOL)YSettopThrash:(NSInteger)THRash;
+ (BOOL)vrightThrash:(NSInteger)THRash;
+ (BOOL)cSetrightThrash:(NSInteger)THRash;
+ (BOOL)RbottomThrash:(NSInteger)THRash;
+ (BOOL)HSetbottomThrash:(NSInteger)THRash;
+ (BOOL)LwidthThrash:(NSInteger)THRash;
+ (BOOL)vSetwidthThrash:(NSInteger)THRash;
+ (BOOL)HheightThrash:(NSInteger)THRash;
+ (BOOL)vSetheightThrash:(NSInteger)THRash;
+ (BOOL)ycenterThrash:(NSInteger)THRash;
+ (BOOL)ySetcenterThrash:(NSInteger)THRash;
+ (BOOL)FcenterXThrash:(NSInteger)THRash;
+ (BOOL)FSetcenterxThrash:(NSInteger)THRash;
+ (BOOL)GcenterYThrash:(NSInteger)THRash;
+ (BOOL)QSetcenteryThrash:(NSInteger)THRash;
+ (BOOL)doriginThrash:(NSInteger)THRash;
+ (BOOL)MSetoriginThrash:(NSInteger)THRash;
+ (BOOL)AframeSizeThrash:(NSInteger)THRash;
+ (BOOL)PSetframesizeThrash:(NSInteger)THRash;
+ (BOOL)wtransformRotationThrash:(NSInteger)THRash;
+ (BOOL)lSettransformrotationThrash:(NSInteger)THRash;
+ (BOOL)UtransformRotationXThrash:(NSInteger)THRash;
+ (BOOL)cSettransformrotationxThrash:(NSInteger)THRash;
+ (BOOL)YtransformRotationYThrash:(NSInteger)THRash;
+ (BOOL)LSettransformrotationyThrash:(NSInteger)THRash;
+ (BOOL)wtransformRotationZThrash:(NSInteger)THRash;
+ (BOOL)nSettransformrotationzThrash:(NSInteger)THRash;
+ (BOOL)ztransformScaleXThrash:(NSInteger)THRash;
+ (BOOL)LSettransformscalexThrash:(NSInteger)THRash;
+ (BOOL)DtransformScaleYThrash:(NSInteger)THRash;
+ (BOOL)vSettransformscaleyThrash:(NSInteger)THRash;
+ (BOOL)xtransformScaleZThrash:(NSInteger)THRash;
+ (BOOL)hSettransformscalezThrash:(NSInteger)THRash;
+ (BOOL)ctransformScaleThrash:(NSInteger)THRash;
+ (BOOL)sSettransformscaleThrash:(NSInteger)THRash;
+ (BOOL)PtransformTranslationXThrash:(NSInteger)THRash;
+ (BOOL)bSettransformtranslationxThrash:(NSInteger)THRash;
+ (BOOL)ItransformTranslationYThrash:(NSInteger)THRash;
+ (BOOL)ySettransformtranslationyThrash:(NSInteger)THRash;
+ (BOOL)ctransformTranslationZThrash:(NSInteger)THRash;
+ (BOOL)KSettransformtranslationzThrash:(NSInteger)THRash;
+ (BOOL)htransformDepthThrash:(NSInteger)THRash;
+ (BOOL)MSettransformdepthThrash:(NSInteger)THRash;
+ (BOOL)fcontentModeThrash:(NSInteger)THRash;
+ (BOOL)mSetcontentmodeThrash:(NSInteger)THRash;
+ (BOOL)yAddfadeanimationwithdurationOCurveThrash:(NSInteger)THRash;
+ (BOOL)SremovePreviousFadeAnimationThrash:(NSInteger)THRash;

@end
