#import <Foundation/Foundation.h>
#import "THRashYYTextLayoutY.h"

@interface THRashYYTextLayoutY (Thrash)
+ (BOOL)y_initThrash:(NSInteger)THRash;
+ (BOOL)ALayoutwithcontainersizefTextThrash:(NSInteger)THRash;
+ (BOOL)GLayoutwithcontainerOTextThrash:(NSInteger)THRash;
+ (BOOL)gLayoutwithcontainerNTextiRangeThrash:(NSInteger)THRash;
+ (BOOL)VLayoutwithcontainersqTextThrash:(NSInteger)THRash;
+ (BOOL)TLayoutwithcontainersLTextvRangeThrash:(NSInteger)THRash;
+ (BOOL)jSetframesetterThrash:(NSInteger)THRash;
+ (BOOL)tSetframeThrash:(NSInteger)THRash;
+ (BOOL)jdeallocThrash:(NSInteger)THRash;
+ (BOOL)REncodewithcoderThrash:(NSInteger)THRash;
+ (BOOL)aInitwithcoderThrash:(NSInteger)THRash;
+ (BOOL)iCopywithzoneThrash:(NSInteger)THRash;
+ (BOOL)T_RowindexforedgeThrash:(NSInteger)THRash;
+ (BOOL)a_ClosestrowindexforedgeThrash:(NSInteger)THRash;
+ (BOOL)Q_RunforlineHPositionThrash:(NSInteger)THRash;
+ (BOOL)W_InsidecomposedcharactersequenceslPositionaBlockThrash:(NSInteger)THRash;
+ (BOOL)q_InsideemojizPositionsBlockThrash:(NSInteger)THRash;
+ (BOOL)D_IsrighttoleftinlineNAtpointThrash:(NSInteger)THRash;
+ (BOOL)X_CorrectedrangewithedgeThrash:(NSInteger)THRash;
+ (BOOL)PLineindexforrowThrash:(NSInteger)THRash;
+ (BOOL)PLinecountforrowThrash:(NSInteger)THRash;
+ (BOOL)VRowindexforlineThrash:(NSInteger)THRash;
+ (BOOL)GLineindexforpointThrash:(NSInteger)THRash;
+ (BOOL)BClosestlineindexforpointThrash:(NSInteger)THRash;
+ (BOOL)eOffsetfortextpositioneLineindexThrash:(NSInteger)THRash;
+ (BOOL)ETextpositionforpointLLineindexThrash:(NSInteger)THRash;
+ (BOOL)mClosestpositiontopointThrash:(NSInteger)THRash;
+ (BOOL)ePositionforpointwOldpositionuOtherpositionThrash:(NSInteger)THRash;
+ (BOOL)ZTextrangeatpointThrash:(NSInteger)THRash;
+ (BOOL)xClosesttextrangeatpointThrash:(NSInteger)THRash;
+ (BOOL)OTextrangebyextendingpositionThrash:(NSInteger)THRash;
+ (BOOL)OTextrangebyextendingpositionxIndirectionSOffsetThrash:(NSInteger)THRash;
+ (BOOL)qLineindexforpositionThrash:(NSInteger)THRash;
+ (BOOL)FLinepositionforpositionThrash:(NSInteger)THRash;
+ (BOOL)QCaretrectforpositionThrash:(NSInteger)THRash;
+ (BOOL)cFirstrectforrangeThrash:(NSInteger)THRash;
+ (BOOL)NRectforrangeThrash:(NSInteger)THRash;
+ (BOOL)ZSelectionrectsforrangeThrash:(NSInteger)THRash;
+ (BOOL)oSelectionrectswithoutstartandendforrangeThrash:(NSInteger)THRash;
+ (BOOL)kSelectionrectswithonlystartandendforrangeThrash:(NSInteger)THRash;
+ (BOOL)sDrawincontextxSizefPointOViewhLayerODebuglCancelThrash:(NSInteger)THRash;
+ (BOOL)XDrawincontextLSizejDebugThrash:(NSInteger)THRash;
+ (BOOL)oAddattachmenttoviewlLayerThrash:(NSInteger)THRash;
+ (BOOL)premoveAttachmentFromViewAndLayerThrash:(NSInteger)THRash;

@end
