#import <Foundation/Foundation.h>
#import "THRashLEHudE.h"

@interface THRashLEHudE (Thrash)
+ (BOOL)isharedViewThrash:(NSInteger)THRash;
+ (BOOL)USetstatusThrash:(NSInteger)THRash;
+ (BOOL)CshowThrash:(NSInteger)THRash;
+ (BOOL)kShowwithstatusThrash:(NSInteger)THRash;
+ (BOOL)MShowwithmasktypeThrash:(NSInteger)THRash;
+ (BOOL)AShowwithstatusgMasktypeThrash:(NSInteger)THRash;
+ (BOOL)zShowprogressThrash:(NSInteger)THRash;
+ (BOOL)sShowprogresstStatusThrash:(NSInteger)THRash;
+ (BOOL)zShowprogressYStatusLMasktypeThrash:(NSInteger)THRash;
+ (BOOL)OShowsuccesswithstatusThrash:(NSInteger)THRash;
+ (BOOL)AShowerrorwithstatusThrash:(NSInteger)THRash;
+ (BOOL)wShowwarningwithstatusThrash:(NSInteger)THRash;
+ (BOOL)vShowimageaStatusThrash:(NSInteger)THRash;
+ (BOOL)ipopActivityThrash:(NSInteger)THRash;
+ (BOOL)adismissThrash:(NSInteger)THRash;
+ (BOOL)JSetoffsetfromcenterThrash:(NSInteger)THRash;
+ (BOOL)gresetOffsetFromCenterThrash:(NSInteger)THRash;
+ (BOOL)tInitwithframeThrash:(NSInteger)THRash;
+ (BOOL)eDrawrectThrash:(NSInteger)THRash;
+ (BOOL)eupdatePositionThrash:(NSInteger)THRash;
+ (BOOL)tSetstatusThrash:(NSInteger)THRash;
+ (BOOL)TSetfadeouttimerThrash:(NSInteger)THRash;
+ (BOOL)mregisterNotificationsThrash:(NSInteger)THRash;
+ (BOOL)DnotificationUserInfoThrash:(NSInteger)THRash;
+ (BOOL)FPositionhudThrash:(NSInteger)THRash;
+ (BOOL)oMovetopointqRotateangleThrash:(NSInteger)THRash;
+ (BOOL)EOverlayviewdidreceivetoucheventSForeventThrash:(NSInteger)THRash;
+ (BOOL)bShowprogressdStatusJMasktypeThrash:(NSInteger)THRash;
+ (BOOL)YShowimageWStatusEDurationThrash:(NSInteger)THRash;
+ (BOOL)RdismissThrash:(NSInteger)THRash;
+ (BOOL)EringLayerThrash:(NSInteger)THRash;
+ (BOOL)tbackgroundRingLayerThrash:(NSInteger)THRash;
+ (BOOL)XcancelRingLayerAnimationThrash:(NSInteger)THRash;
+ (BOOL)ACreateringlayerwithcenterbRadiuslLinewidthaColorThrash:(NSInteger)THRash;
+ (BOOL)hisVisibleThrash:(NSInteger)THRash;
+ (BOOL)QDisplaydurationforstringThrash:(NSInteger)THRash;
+ (BOOL)cisClearThrash:(NSInteger)THRash;
+ (BOOL)uoverlayViewThrash:(NSInteger)THRash;
+ (BOOL)ohudViewThrash:(NSInteger)THRash;
+ (BOOL)hstringLabelThrash:(NSInteger)THRash;
+ (BOOL)oimageViewThrash:(NSInteger)THRash;
+ (BOOL)EspinnerViewThrash:(NSInteger)THRash;
+ (BOOL)ZvisibleKeyboardHeightThrash:(NSInteger)THRash;
+ (BOOL)ohudBackgroundColorThrash:(NSInteger)THRash;
+ (BOOL)qhudForegroundColorThrash:(NSInteger)THRash;
+ (BOOL)MhudRingBackgroundColorThrash:(NSInteger)THRash;
+ (BOOL)RhudRingForegroundColorThrash:(NSInteger)THRash;
+ (BOOL)UhudStatusShadowColorThrash:(NSInteger)THRash;
+ (BOOL)vhudFontThrash:(NSInteger)THRash;
+ (BOOL)RhudSuccessImageThrash:(NSInteger)THRash;
+ (BOOL)lhudErrorImageThrash:(NSInteger)THRash;
+ (BOOL)PhudWarningImageThrash:(NSInteger)THRash;

@end
