#import <Foundation/Foundation.h>
#import "THRashYYKVStorageItemF.h"

@interface THRashYYKVStorageItemF (Thrash)
+ (BOOL)D_dbOpenThrash:(NSInteger)THRash;
+ (BOOL)B_dbCloseThrash:(NSInteger)THRash;
+ (BOOL)L_dbCheckThrash:(NSInteger)THRash;
+ (BOOL)J_dbInitializeThrash:(NSInteger)THRash;
+ (BOOL)J_dbCheckpointThrash:(NSInteger)THRash;
+ (BOOL)p_DbexecuteThrash:(NSInteger)THRash;
+ (BOOL)U_DbpreparestmtThrash:(NSInteger)THRash;
+ (BOOL)I_DbjoinedkeysThrash:(NSInteger)THRash;
+ (BOOL)X_DbbindjoinedkeysSStmtEFromindexThrash:(NSInteger)THRash;
+ (BOOL)c_DbsavewithkeyoValueDFilenameyExtendeddataThrash:(NSInteger)THRash;
+ (BOOL)B_DbupdateaccesstimewithkeyThrash:(NSInteger)THRash;
+ (BOOL)x_DbupdateaccesstimewithkeysThrash:(NSInteger)THRash;
+ (BOOL)S_DbdeleteitemwithkeyThrash:(NSInteger)THRash;
+ (BOOL)d_DbdeleteitemwithkeysThrash:(NSInteger)THRash;
+ (BOOL)K_DbdeleteitemswithsizelargerthanThrash:(NSInteger)THRash;
+ (BOOL)i_DbdeleteitemswithtimeearlierthanThrash:(NSInteger)THRash;
+ (BOOL)L_DbgetitemfromstmtmExcludeinlinedataThrash:(NSInteger)THRash;
+ (BOOL)n_DbgetitemwithkeymExcludeinlinedataThrash:(NSInteger)THRash;
+ (BOOL)V_DbgetitemwithkeysYExcludeinlinedataThrash:(NSInteger)THRash;
+ (BOOL)B_DbgetvaluewithkeyThrash:(NSInteger)THRash;
+ (BOOL)u_DbgetfilenamewithkeyThrash:(NSInteger)THRash;
+ (BOOL)i_DbgetfilenamewithkeysThrash:(NSInteger)THRash;
+ (BOOL)W_DbgetfilenameswithsizelargerthanThrash:(NSInteger)THRash;
+ (BOOL)s_DbgetfilenameswithtimeearlierthanThrash:(NSInteger)THRash;
+ (BOOL)x_DbgetitemsizeinfoorderbytimeascwithlimitThrash:(NSInteger)THRash;
+ (BOOL)Y_DbgetitemcountwithkeyThrash:(NSInteger)THRash;
+ (BOOL)g_dbGetTotalItemSizeThrash:(NSInteger)THRash;
+ (BOOL)M_dbGetTotalItemCountThrash:(NSInteger)THRash;
+ (BOOL)z_FilewritewithnameNDataThrash:(NSInteger)THRash;
+ (BOOL)P_FilereadwithnameThrash:(NSInteger)THRash;
+ (BOOL)m_FiledeletewithnameThrash:(NSInteger)THRash;
+ (BOOL)X_fileMoveAllToTrashThrash:(NSInteger)THRash;
+ (BOOL)z_fileEmptyTrashInBackgroundThrash:(NSInteger)THRash;
+ (BOOL)u_resetThrash:(NSInteger)THRash;
+ (BOOL)dinitThrash:(NSInteger)THRash;
+ (BOOL)YInitwithpathgTypeThrash:(NSInteger)THRash;
+ (BOOL)WdeallocThrash:(NSInteger)THRash;
+ (BOOL)vSaveitemThrash:(NSInteger)THRash;
+ (BOOL)QSaveitemwithkeyeValueThrash:(NSInteger)THRash;
+ (BOOL)aSaveitemwithkeypValueKFilenameTExtendeddataThrash:(NSInteger)THRash;
+ (BOOL)iRemoveitemforkeyThrash:(NSInteger)THRash;
+ (BOOL)yRemoveitemforkeysThrash:(NSInteger)THRash;
+ (BOOL)URemoveitemslargerthansizeThrash:(NSInteger)THRash;
+ (BOOL)QRemoveitemsearlierthantimeThrash:(NSInteger)THRash;
+ (BOOL)HRemoveitemstofitsizeThrash:(NSInteger)THRash;
+ (BOOL)bRemoveitemstofitcountThrash:(NSInteger)THRash;
+ (BOOL)nremoveAllItemsThrash:(NSInteger)THRash;
+ (BOOL)uRemoveallitemswithprogressblockMEndblockThrash:(NSInteger)THRash;
+ (BOOL)JGetitemforkeyThrash:(NSInteger)THRash;
+ (BOOL)xGetiteminfoforkeyThrash:(NSInteger)THRash;
+ (BOOL)CGetitemvalueforkeyThrash:(NSInteger)THRash;
+ (BOOL)SGetitemforkeysThrash:(NSInteger)THRash;
+ (BOOL)fGetiteminfoforkeysThrash:(NSInteger)THRash;
+ (BOOL)YGetitemvalueforkeysThrash:(NSInteger)THRash;
+ (BOOL)pItemexistsforkeyThrash:(NSInteger)THRash;
+ (BOOL)LgetItemsCountThrash:(NSInteger)THRash;
+ (BOOL)KgetItemsSizeThrash:(NSInteger)THRash;

@end
