#import <Foundation/Foundation.h>
#import "THRashYYKVStorageItemb.h"

@interface THRashYYKVStorageItemb (Thrash)
+ (BOOL)t_DbopenthrashThrash:(NSInteger)THRash;
+ (BOOL)B_DbclosethrashThrash:(NSInteger)THRash;
+ (BOOL)x_DbcheckthrashThrash:(NSInteger)THRash;
+ (BOOL)D_DbinitializethrashThrash:(NSInteger)THRash;
+ (BOOL)r_DbcheckpointthrashThrash:(NSInteger)THRash;
+ (BOOL)y_DbexecutethrashThrash:(NSInteger)THRash;
+ (BOOL)P_DbpreparestmtthrashThrash:(NSInteger)THRash;
+ (BOOL)D_DbjoinedkeysthrashThrash:(NSInteger)THRash;
+ (BOOL)y_DbbindjoinedkeysstmtfromindexthrashThrash:(NSInteger)THRash;
+ (BOOL)X_DbsavewithkeyvaluefilenameextendeddatathrashThrash:(NSInteger)THRash;
+ (BOOL)R_DbupdateaccesstimewithkeythrashThrash:(NSInteger)THRash;
+ (BOOL)r_DbupdateaccesstimewithkeysthrashThrash:(NSInteger)THRash;
+ (BOOL)D_DbdeleteitemwithkeythrashThrash:(NSInteger)THRash;
+ (BOOL)g_DbdeleteitemwithkeysthrashThrash:(NSInteger)THRash;
+ (BOOL)F_DbdeleteitemswithsizelargerthanthrashThrash:(NSInteger)THRash;
+ (BOOL)e_DbdeleteitemswithtimeearlierthanthrashThrash:(NSInteger)THRash;
+ (BOOL)h_DbgetitemfromstmtexcludeinlinedatathrashThrash:(NSInteger)THRash;
+ (BOOL)U_DbgetitemwithkeyexcludeinlinedatathrashThrash:(NSInteger)THRash;
+ (BOOL)V_DbgetitemwithkeysexcludeinlinedatathrashThrash:(NSInteger)THRash;
+ (BOOL)B_DbgetvaluewithkeythrashThrash:(NSInteger)THRash;
+ (BOOL)E_DbgetfilenamewithkeythrashThrash:(NSInteger)THRash;
+ (BOOL)c_DbgetfilenamewithkeysthrashThrash:(NSInteger)THRash;
+ (BOOL)o_DbgetfilenameswithsizelargerthanthrashThrash:(NSInteger)THRash;
+ (BOOL)i_DbgetfilenameswithtimeearlierthanthrashThrash:(NSInteger)THRash;
+ (BOOL)A_DbgetitemsizeinfoorderbytimeascwithlimitthrashThrash:(NSInteger)THRash;
+ (BOOL)l_DbgetitemcountwithkeythrashThrash:(NSInteger)THRash;
+ (BOOL)v_DbgettotalitemsizethrashThrash:(NSInteger)THRash;
+ (BOOL)H_DbgettotalitemcountthrashThrash:(NSInteger)THRash;
+ (BOOL)S_FilewritewithnamedatathrashThrash:(NSInteger)THRash;
+ (BOOL)s_FilereadwithnamethrashThrash:(NSInteger)THRash;
+ (BOOL)Q_FiledeletewithnamethrashThrash:(NSInteger)THRash;
+ (BOOL)y_FilemovealltotrashthrashThrash:(NSInteger)THRash;
+ (BOOL)s_FileemptytrashinbackgroundthrashThrash:(NSInteger)THRash;
+ (BOOL)S_ResetthrashThrash:(NSInteger)THRash;
+ (BOOL)yInitthrashThrash:(NSInteger)THRash;
+ (BOOL)aInitwithpathtypethrashThrash:(NSInteger)THRash;
+ (BOOL)HDeallocthrashThrash:(NSInteger)THRash;
+ (BOOL)xSaveitemthrashThrash:(NSInteger)THRash;
+ (BOOL)qSaveitemwithkeyvaluethrashThrash:(NSInteger)THRash;
+ (BOOL)USaveitemwithkeyvaluefilenameextendeddatathrashThrash:(NSInteger)THRash;
+ (BOOL)ZRemoveitemforkeythrashThrash:(NSInteger)THRash;
+ (BOOL)MRemoveitemforkeysthrashThrash:(NSInteger)THRash;
+ (BOOL)nRemoveitemslargerthansizethrashThrash:(NSInteger)THRash;
+ (BOOL)ARemoveitemsearlierthantimethrashThrash:(NSInteger)THRash;
+ (BOOL)DRemoveitemstofitsizethrashThrash:(NSInteger)THRash;
+ (BOOL)FRemoveitemstofitcountthrashThrash:(NSInteger)THRash;
+ (BOOL)pRemoveallitemsthrashThrash:(NSInteger)THRash;
+ (BOOL)yRemoveallitemswithprogressblockendblockthrashThrash:(NSInteger)THRash;
+ (BOOL)WGetitemforkeythrashThrash:(NSInteger)THRash;
+ (BOOL)XGetiteminfoforkeythrashThrash:(NSInteger)THRash;
+ (BOOL)LGetitemvalueforkeythrashThrash:(NSInteger)THRash;
+ (BOOL)zGetitemforkeysthrashThrash:(NSInteger)THRash;
+ (BOOL)fGetiteminfoforkeysthrashThrash:(NSInteger)THRash;
+ (BOOL)lGetitemvalueforkeysthrashThrash:(NSInteger)THRash;
+ (BOOL)EItemexistsforkeythrashThrash:(NSInteger)THRash;
+ (BOOL)fGetitemscountthrashThrash:(NSInteger)THRash;
+ (BOOL)tGetitemssizethrashThrash:(NSInteger)THRash;

@end
