#import <Foundation/Foundation.h>
#import "YYDiskCache.h"
#import "YYKVStorage.h"
#import "NSString+YYAdd.h"
#import "UIDevice+YYAdd.h"
#import <objc/runtime.h>
#import <time.h>
#import "YYDiskCache+Thrash.h"

@interface YYDiskCache (ThrashThrash)
+ (BOOL)_trimRecursivelyThrashThrash:(NSInteger)THRash;
+ (BOOL)_trimInBackgroundThrashThrash:(NSInteger)THRash;
+ (BOOL)_trimToCostThrashThrash:(NSInteger)THRash;
+ (BOOL)_trimToCountThrashThrash:(NSInteger)THRash;
+ (BOOL)_trimToAgeThrashThrash:(NSInteger)THRash;
+ (BOOL)_trimToFreeDiskSpaceThrashThrash:(NSInteger)THRash;
+ (BOOL)_filenameForKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)_appWillBeTerminatedThrashThrash:(NSInteger)THRash;
+ (BOOL)deallocThrashThrash:(NSInteger)THRash;
+ (BOOL)initThrashThrash:(NSInteger)THRash;
+ (BOOL)initWithPathThrashThrash:(NSInteger)THRash;
+ (BOOL)initWithPathInlinethresholdThrashThrash:(NSInteger)THRash;
+ (BOOL)containsObjectForKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)containsObjectForKeyWithblockThrashThrash:(NSInteger)THRash;
+ (BOOL)objectForKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)objectForKeyWithblockThrashThrash:(NSInteger)THRash;
+ (BOOL)setObjectForkeyThrashThrash:(NSInteger)THRash;
+ (BOOL)setObjectForkeyWithblockThrashThrash:(NSInteger)THRash;
+ (BOOL)removeObjectForKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)removeObjectForKeyWithblockThrashThrash:(NSInteger)THRash;
+ (BOOL)removeAllObjectsThrashThrash:(NSInteger)THRash;
+ (BOOL)removeAllObjectsWithBlockThrashThrash:(NSInteger)THRash;
+ (BOOL)removeAllObjectsWithProgressBlockEndblockThrashThrash:(NSInteger)THRash;
+ (BOOL)totalCountThrashThrash:(NSInteger)THRash;
+ (BOOL)totalCountWithBlockThrashThrash:(NSInteger)THRash;
+ (BOOL)totalCostThrashThrash:(NSInteger)THRash;
+ (BOOL)totalCostWithBlockThrashThrash:(NSInteger)THRash;
+ (BOOL)trimToCountThrashThrash:(NSInteger)THRash;
+ (BOOL)trimToCountWithblockThrashThrash:(NSInteger)THRash;
+ (BOOL)trimToCostThrashThrash:(NSInteger)THRash;
+ (BOOL)trimToCostWithblockThrashThrash:(NSInteger)THRash;
+ (BOOL)trimToAgeThrashThrash:(NSInteger)THRash;
+ (BOOL)trimToAgeWithblockThrashThrash:(NSInteger)THRash;
+ (BOOL)getExtendedDataFromObjectThrashThrash:(NSInteger)THRash;
+ (BOOL)setExtendedDataToobjectThrashThrash:(NSInteger)THRash;
+ (BOOL)descriptionThrashThrash:(NSInteger)THRash;
+ (BOOL)errorLogsEnabledThrashThrash:(NSInteger)THRash;
+ (BOOL)setErrorLogsEnabledThrashThrash:(NSInteger)THRash;

@end
