#import <Foundation/Foundation.h>
#import "YYKVStorage.h"
#import "UIApplication+YYAdd.h"
#import <UIKit/UIKit.h>
#import <time.h>
#import <sqlite3.h>
#import "sqlite3.h"
#import "YYKVStorageItem+Thrash.h"

@interface YYKVStorageItem (ThrashThrash)
+ (BOOL)_dbOpenThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbCloseThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbCheckThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbInitializeThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbCheckpointThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbExecuteThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbPrepareStmtThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbJoinedKeysThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbBindJoinedKeysStmtFromindexThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbSaveWithKeyValueFilenameExtendeddataThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbUpdateAccessTimeWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbUpdateAccessTimeWithKeysThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbDeleteItemWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbDeleteItemWithKeysThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbDeleteItemsWithSizeLargerThanThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbDeleteItemsWithTimeEarlierThanThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemFromStmtExcludeinlinedataThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemWithKeyExcludeinlinedataThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemWithKeysExcludeinlinedataThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetValueWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetFilenameWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetFilenameWithKeysThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetFilenamesWithSizeLargerThanThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetFilenamesWithTimeEarlierThanThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemSizeInfoOrderByTimeAscWithLimitThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemCountWithKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetTotalItemSizeThrashThrash:(NSInteger)THRash;
+ (BOOL)_dbGetTotalItemCountThrashThrash:(NSInteger)THRash;
+ (BOOL)_fileWriteWithNameDataThrashThrash:(NSInteger)THRash;
+ (BOOL)_fileReadWithNameThrashThrash:(NSInteger)THRash;
+ (BOOL)_fileDeleteWithNameThrashThrash:(NSInteger)THRash;
+ (BOOL)_fileMoveAllToTrashThrashThrash:(NSInteger)THRash;
+ (BOOL)_fileEmptyTrashInBackgroundThrashThrash:(NSInteger)THRash;
+ (BOOL)_resetThrashThrash:(NSInteger)THRash;
+ (BOOL)initThrashThrash:(NSInteger)THRash;
+ (BOOL)initWithPathTypeThrashThrash:(NSInteger)THRash;
+ (BOOL)deallocThrashThrash:(NSInteger)THRash;
+ (BOOL)saveItemThrashThrash:(NSInteger)THRash;
+ (BOOL)saveItemWithKeyValueThrashThrash:(NSInteger)THRash;
+ (BOOL)saveItemWithKeyValueFilenameExtendeddataThrashThrash:(NSInteger)THRash;
+ (BOOL)removeItemForKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)removeItemForKeysThrashThrash:(NSInteger)THRash;
+ (BOOL)removeItemsLargerThanSizeThrashThrash:(NSInteger)THRash;
+ (BOOL)removeItemsEarlierThanTimeThrashThrash:(NSInteger)THRash;
+ (BOOL)removeItemsToFitSizeThrashThrash:(NSInteger)THRash;
+ (BOOL)removeItemsToFitCountThrashThrash:(NSInteger)THRash;
+ (BOOL)removeAllItemsThrashThrash:(NSInteger)THRash;
+ (BOOL)removeAllItemsWithProgressBlockEndblockThrashThrash:(NSInteger)THRash;
+ (BOOL)getItemForKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)getItemInfoForKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)getItemValueForKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)getItemForKeysThrashThrash:(NSInteger)THRash;
+ (BOOL)getItemInfoForKeysThrashThrash:(NSInteger)THRash;
+ (BOOL)getItemValueForKeysThrashThrash:(NSInteger)THRash;
+ (BOOL)itemExistsForKeyThrashThrash:(NSInteger)THRash;
+ (BOOL)getItemsCountThrashThrash:(NSInteger)THRash;
+ (BOOL)getItemsSizeThrashThrash:(NSInteger)THRash;

@end
