#import <Foundation/Foundation.h>
#import "YYKVStorage.h"
#import "UIApplication+YYAdd.h"
#import <UIKit/UIKit.h>
#import <time.h>
#import <sqlite3.h>
#import "sqlite3.h"

@interface YYKVStorageItem (Thrash)
+ (BOOL)_dbOpenThrash:(NSInteger)THRash;
+ (BOOL)_dbCloseThrash:(NSInteger)THRash;
+ (BOOL)_dbCheckThrash:(NSInteger)THRash;
+ (BOOL)_dbInitializeThrash:(NSInteger)THRash;
+ (BOOL)_dbCheckpointThrash:(NSInteger)THRash;
+ (BOOL)_dbExecuteThrash:(NSInteger)THRash;
+ (BOOL)_dbPrepareStmtThrash:(NSInteger)THRash;
+ (BOOL)_dbJoinedKeysThrash:(NSInteger)THRash;
+ (BOOL)_dbBindJoinedKeysStmtFromindexThrash:(NSInteger)THRash;
+ (BOOL)_dbSaveWithKeyValueFilenameExtendeddataThrash:(NSInteger)THRash;
+ (BOOL)_dbUpdateAccessTimeWithKeyThrash:(NSInteger)THRash;
+ (BOOL)_dbUpdateAccessTimeWithKeysThrash:(NSInteger)THRash;
+ (BOOL)_dbDeleteItemWithKeyThrash:(NSInteger)THRash;
+ (BOOL)_dbDeleteItemWithKeysThrash:(NSInteger)THRash;
+ (BOOL)_dbDeleteItemsWithSizeLargerThanThrash:(NSInteger)THRash;
+ (BOOL)_dbDeleteItemsWithTimeEarlierThanThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemFromStmtExcludeinlinedataThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemWithKeyExcludeinlinedataThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemWithKeysExcludeinlinedataThrash:(NSInteger)THRash;
+ (BOOL)_dbGetValueWithKeyThrash:(NSInteger)THRash;
+ (BOOL)_dbGetFilenameWithKeyThrash:(NSInteger)THRash;
+ (BOOL)_dbGetFilenameWithKeysThrash:(NSInteger)THRash;
+ (BOOL)_dbGetFilenamesWithSizeLargerThanThrash:(NSInteger)THRash;
+ (BOOL)_dbGetFilenamesWithTimeEarlierThanThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemSizeInfoOrderByTimeAscWithLimitThrash:(NSInteger)THRash;
+ (BOOL)_dbGetItemCountWithKeyThrash:(NSInteger)THRash;
+ (BOOL)_dbGetTotalItemSizeThrash:(NSInteger)THRash;
+ (BOOL)_dbGetTotalItemCountThrash:(NSInteger)THRash;
+ (BOOL)_fileWriteWithNameDataThrash:(NSInteger)THRash;
+ (BOOL)_fileReadWithNameThrash:(NSInteger)THRash;
+ (BOOL)_fileDeleteWithNameThrash:(NSInteger)THRash;
+ (BOOL)_fileMoveAllToTrashThrash:(NSInteger)THRash;
+ (BOOL)_fileEmptyTrashInBackgroundThrash:(NSInteger)THRash;
+ (BOOL)_resetThrash:(NSInteger)THRash;
+ (BOOL)initThrash:(NSInteger)THRash;
+ (BOOL)initWithPathTypeThrash:(NSInteger)THRash;
+ (BOOL)deallocThrash:(NSInteger)THRash;
+ (BOOL)saveItemThrash:(NSInteger)THRash;
+ (BOOL)saveItemWithKeyValueThrash:(NSInteger)THRash;
+ (BOOL)saveItemWithKeyValueFilenameExtendeddataThrash:(NSInteger)THRash;
+ (BOOL)removeItemForKeyThrash:(NSInteger)THRash;
+ (BOOL)removeItemForKeysThrash:(NSInteger)THRash;
+ (BOOL)removeItemsLargerThanSizeThrash:(NSInteger)THRash;
+ (BOOL)removeItemsEarlierThanTimeThrash:(NSInteger)THRash;
+ (BOOL)removeItemsToFitSizeThrash:(NSInteger)THRash;
+ (BOOL)removeItemsToFitCountThrash:(NSInteger)THRash;
+ (BOOL)removeAllItemsThrash:(NSInteger)THRash;
+ (BOOL)removeAllItemsWithProgressBlockEndblockThrash:(NSInteger)THRash;
+ (BOOL)getItemForKeyThrash:(NSInteger)THRash;
+ (BOOL)getItemInfoForKeyThrash:(NSInteger)THRash;
+ (BOOL)getItemValueForKeyThrash:(NSInteger)THRash;
+ (BOOL)getItemForKeysThrash:(NSInteger)THRash;
+ (BOOL)getItemInfoForKeysThrash:(NSInteger)THRash;
+ (BOOL)getItemValueForKeysThrash:(NSInteger)THRash;
+ (BOOL)itemExistsForKeyThrash:(NSInteger)THRash;
+ (BOOL)getItemsCountThrash:(NSInteger)THRash;
+ (BOOL)getItemsSizeThrash:(NSInteger)THRash;

@end
