#import <UIKit/UIKit.h>
#import <YYKit/YYTextParser.h>
#import <YYKit/YYTextLayout.h>
#import <YYKit/YYTextAttribute.h>
#import "YYTextParser.h"
#import "YYTextLayout.h"
#import "YYTextAttribute.h"
#import "YYLabel.h"
#import "YYAsyncLayer.h"
#import "YYWeakProxy.h"
#import "YYCGUtilities.h"
#import "NSAttributedString+YYText.h"
#import "YYDispatchQueuePool.h"
#import "YYLabel+Thrash.h"

@interface YYLabel (ThrashThrash)
+ (BOOL)_updateIfNeededThrashThrash:(NSInteger)THRash;
+ (BOOL)_updateLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)_setLayoutNeedUpdateThrashThrash:(NSInteger)THRash;
+ (BOOL)_setLayoutNeedRedrawThrashThrash:(NSInteger)THRash;
+ (BOOL)_clearInnerLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)_innerLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)_highlightLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)_shrinkLayoutWithLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)_startLongPressTimerThrashThrash:(NSInteger)THRash;
+ (BOOL)_endLongPressTimerThrashThrash:(NSInteger)THRash;
+ (BOOL)_trackDidLongPressThrashThrash:(NSInteger)THRash;
+ (BOOL)_getHighlightAtPointRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)_showHighlightAnimatedThrashThrash:(NSInteger)THRash;
+ (BOOL)_hideHighlightAnimatedThrashThrash:(NSInteger)THRash;
+ (BOOL)_removeHighlightAnimatedThrashThrash:(NSInteger)THRash;
+ (BOOL)_endTouchThrashThrash:(NSInteger)THRash;
+ (BOOL)_convertPointToLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)_convertPointFromLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)_convertRectToLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)_convertRectFromLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)_defaultFontThrashThrash:(NSInteger)THRash;
+ (BOOL)_shadowFromPropertiesThrashThrash:(NSInteger)THRash;
+ (BOOL)_updateOuterLineBreakModeThrashThrash:(NSInteger)THRash;
+ (BOOL)_updateOuterTextPropertiesThrashThrash:(NSInteger)THRash;
+ (BOOL)_updateOuterContainerPropertiesThrashThrash:(NSInteger)THRash;
+ (BOOL)_clearContentsThrashThrash:(NSInteger)THRash;
+ (BOOL)_initLabelThrashThrash:(NSInteger)THRash;
+ (BOOL)initWithFrameThrashThrash:(NSInteger)THRash;
+ (BOOL)deallocThrashThrash:(NSInteger)THRash;
+ (BOOL)layerClassThrashThrash:(NSInteger)THRash;
+ (BOOL)setFrameThrashThrash:(NSInteger)THRash;
+ (BOOL)setBoundsThrashThrash:(NSInteger)THRash;
+ (BOOL)sizeThatFitsThrashThrash:(NSInteger)THRash;
+ (BOOL)accessibilityLabelThrashThrash:(NSInteger)THRash;
+ (BOOL)encodeWithCoderThrashThrash:(NSInteger)THRash;
+ (BOOL)initWithCoderThrashThrash:(NSInteger)THRash;
+ (BOOL)touchesBeganWitheventThrashThrash:(NSInteger)THRash;
+ (BOOL)touchesMovedWitheventThrashThrash:(NSInteger)THRash;
+ (BOOL)touchesEndedWitheventThrashThrash:(NSInteger)THRash;
+ (BOOL)touchesCancelledWitheventThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextThrashThrash:(NSInteger)THRash;
+ (BOOL)setFontThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextColorThrashThrash:(NSInteger)THRash;
+ (BOOL)setShadowColorThrashThrash:(NSInteger)THRash;
+ (BOOL)setShadowOffsetThrashThrash:(NSInteger)THRash;
+ (BOOL)setShadowOffsetThrashThrash:(NSInteger)THRash;
+ (BOOL)setShadowBlurRadiusThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextAlignmentThrashThrash:(NSInteger)THRash;
+ (BOOL)setLineBreakModeThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextVerticalAlignmentThrashThrash:(NSInteger)THRash;
+ (BOOL)setTruncationTokenThrashThrash:(NSInteger)THRash;
+ (BOOL)setNumberOfLinesThrashThrash:(NSInteger)THRash;
+ (BOOL)setAttributedTextThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextContainerPathThrashThrash:(NSInteger)THRash;
+ (BOOL)setExclusionPathsThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextContainerInsetThrashThrash:(NSInteger)THRash;
+ (BOOL)setVerticalFormThrashThrash:(NSInteger)THRash;
+ (BOOL)setLinePositionModifierThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextParserThrashThrash:(NSInteger)THRash;
+ (BOOL)setTextLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)textLayoutThrashThrash:(NSInteger)THRash;
+ (BOOL)setDisplaysAsynchronouslyThrashThrash:(NSInteger)THRash;
+ (BOOL)setPreferredMaxLayoutWidthThrashThrash:(NSInteger)THRash;
+ (BOOL)intrinsicContentSizeThrashThrash:(NSInteger)THRash;
+ (BOOL)setDebugOptionThrashThrash:(NSInteger)THRash;
+ (BOOL)newAsyncDisplayTaskThrashThrash:(NSInteger)THRash;

@end
