#import <UIKit/UIKit.h>
#import <CoreText/CoreText.h>
#import <YYKit/YYTextDebugOption.h>
#import <YYKit/YYTextLine.h>
#import <YYKit/YYTextInput.h>
#import "YYTextDebugOption.h"
#import "YYTextLine.h"
#import "YYTextInput.h"
#import "YYTextLayout.h"
#import "YYKitMacro.h"
#import "YYCGUtilities.h"
#import "YYTextUtilities.h"
#import "YYTextAttribute.h"
#import "YYTextArchiver.h"
#import "NSAttributedString+YYText.h"
#import "UIFont+YYAdd.h"

@interface YYTextLayout (Thrash)
+ (BOOL)_initThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainerSizeTextThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainerTextThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainerTextRangeThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainersTextThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainersTextRangeThrash:(NSInteger)THRash;
+ (BOOL)setFrameSetterThrash:(NSInteger)THRash;
+ (BOOL)setFrameThrash:(NSInteger)THRash;
+ (BOOL)deallocThrash:(NSInteger)THRash;
+ (BOOL)encodeWithCoderThrash:(NSInteger)THRash;
+ (BOOL)initWithCoderThrash:(NSInteger)THRash;
+ (BOOL)copyWithZoneThrash:(NSInteger)THRash;
+ (BOOL)_rowIndexForEdgeThrash:(NSInteger)THRash;
+ (BOOL)_closestRowIndexForEdgeThrash:(NSInteger)THRash;
+ (BOOL)_runForLinePositionThrash:(NSInteger)THRash;
+ (BOOL)_insideComposedCharacterSequencesPositionBlockThrash:(NSInteger)THRash;
+ (BOOL)_insideEmojiPositionBlockThrash:(NSInteger)THRash;
+ (BOOL)_isRightToLeftInLineAtpointThrash:(NSInteger)THRash;
+ (BOOL)_correctedRangeWithEdgeThrash:(NSInteger)THRash;
+ (BOOL)lineIndexForRowThrash:(NSInteger)THRash;
+ (BOOL)lineCountForRowThrash:(NSInteger)THRash;
+ (BOOL)rowIndexForLineThrash:(NSInteger)THRash;
+ (BOOL)lineIndexForPointThrash:(NSInteger)THRash;
+ (BOOL)closestLineIndexForPointThrash:(NSInteger)THRash;
+ (BOOL)offsetForTextPositionLineindexThrash:(NSInteger)THRash;
+ (BOOL)textPositionForPointLineindexThrash:(NSInteger)THRash;
+ (BOOL)closestPositionToPointThrash:(NSInteger)THRash;
+ (BOOL)positionForPointOldpositionOtherpositionThrash:(NSInteger)THRash;
+ (BOOL)textRangeAtPointThrash:(NSInteger)THRash;
+ (BOOL)closestTextRangeAtPointThrash:(NSInteger)THRash;
+ (BOOL)textRangeByExtendingPositionThrash:(NSInteger)THRash;
+ (BOOL)textRangeByExtendingPositionIndirectionOffsetThrash:(NSInteger)THRash;
+ (BOOL)lineIndexForPositionThrash:(NSInteger)THRash;
+ (BOOL)linePositionForPositionThrash:(NSInteger)THRash;
+ (BOOL)caretRectForPositionThrash:(NSInteger)THRash;
+ (BOOL)firstRectForRangeThrash:(NSInteger)THRash;
+ (BOOL)rectForRangeThrash:(NSInteger)THRash;
+ (BOOL)selectionRectsForRangeThrash:(NSInteger)THRash;
+ (BOOL)selectionRectsWithoutStartAndEndForRangeThrash:(NSInteger)THRash;
+ (BOOL)selectionRectsWithOnlyStartAndEndForRangeThrash:(NSInteger)THRash;
+ (BOOL)drawInContextSizePointViewLayerDebugCancelThrash:(NSInteger)THRash;
+ (BOOL)drawInContextSizeDebugThrash:(NSInteger)THRash;
+ (BOOL)addAttachmentToViewLayerThrash:(NSInteger)THRash;
+ (BOOL)removeAttachmentFromViewAndLayerThrash:(NSInteger)THRash;

@end
