#import <UIKit/UIKit.h>
#import <CoreText/CoreText.h>
#import <YYKit/YYTextDebugOption.h>
#import <YYKit/YYTextLine.h>
#import <YYKit/YYTextInput.h>
#import "YYTextDebugOption.h"
#import "YYTextLine.h"
#import "YYTextInput.h"
#import "YYTextLayout.h"
#import "YYKitMacro.h"
#import "YYCGUtilities.h"
#import "YYTextUtilities.h"
#import "YYTextAttribute.h"
#import "YYTextArchiver.h"
#import "NSAttributedString+YYText.h"
#import "UIFont+YYAdd.h"
#import "YYTextLayout+Thrash.h"

@interface YYTextLayout (ThrashThrash)
+ (BOOL)_initThrashThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainerSizeTextThrashThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainerTextThrashThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainerTextRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainersTextThrashThrash:(NSInteger)THRash;
+ (BOOL)layoutWithContainersTextRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)setFrameSetterThrashThrash:(NSInteger)THRash;
+ (BOOL)setFrameThrashThrash:(NSInteger)THRash;
+ (BOOL)deallocThrashThrash:(NSInteger)THRash;
+ (BOOL)encodeWithCoderThrashThrash:(NSInteger)THRash;
+ (BOOL)initWithCoderThrashThrash:(NSInteger)THRash;
+ (BOOL)copyWithZoneThrashThrash:(NSInteger)THRash;
+ (BOOL)_rowIndexForEdgeThrashThrash:(NSInteger)THRash;
+ (BOOL)_closestRowIndexForEdgeThrashThrash:(NSInteger)THRash;
+ (BOOL)_runForLinePositionThrashThrash:(NSInteger)THRash;
+ (BOOL)_insideComposedCharacterSequencesPositionBlockThrashThrash:(NSInteger)THRash;
+ (BOOL)_insideEmojiPositionBlockThrashThrash:(NSInteger)THRash;
+ (BOOL)_isRightToLeftInLineAtpointThrashThrash:(NSInteger)THRash;
+ (BOOL)_correctedRangeWithEdgeThrashThrash:(NSInteger)THRash;
+ (BOOL)lineIndexForRowThrashThrash:(NSInteger)THRash;
+ (BOOL)lineCountForRowThrashThrash:(NSInteger)THRash;
+ (BOOL)rowIndexForLineThrashThrash:(NSInteger)THRash;
+ (BOOL)lineIndexForPointThrashThrash:(NSInteger)THRash;
+ (BOOL)closestLineIndexForPointThrashThrash:(NSInteger)THRash;
+ (BOOL)offsetForTextPositionLineindexThrashThrash:(NSInteger)THRash;
+ (BOOL)textPositionForPointLineindexThrashThrash:(NSInteger)THRash;
+ (BOOL)closestPositionToPointThrashThrash:(NSInteger)THRash;
+ (BOOL)positionForPointOldpositionOtherpositionThrashThrash:(NSInteger)THRash;
+ (BOOL)textRangeAtPointThrashThrash:(NSInteger)THRash;
+ (BOOL)closestTextRangeAtPointThrashThrash:(NSInteger)THRash;
+ (BOOL)textRangeByExtendingPositionThrashThrash:(NSInteger)THRash;
+ (BOOL)textRangeByExtendingPositionIndirectionOffsetThrashThrash:(NSInteger)THRash;
+ (BOOL)lineIndexForPositionThrashThrash:(NSInteger)THRash;
+ (BOOL)linePositionForPositionThrashThrash:(NSInteger)THRash;
+ (BOOL)caretRectForPositionThrashThrash:(NSInteger)THRash;
+ (BOOL)firstRectForRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)rectForRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)selectionRectsForRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)selectionRectsWithoutStartAndEndForRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)selectionRectsWithOnlyStartAndEndForRangeThrashThrash:(NSInteger)THRash;
+ (BOOL)drawInContextSizePointViewLayerDebugCancelThrashThrash:(NSInteger)THRash;
+ (BOOL)drawInContextSizeDebugThrashThrash:(NSInteger)THRash;
+ (BOOL)addAttachmentToViewLayerThrashThrash:(NSInteger)THRash;
+ (BOOL)removeAttachmentFromViewAndLayerThrashThrash:(NSInteger)THRash;

@end
