#import <Foundation/Foundation.h>
@interface THRashTHRashSDImageCacheKm: NSObject
+ (BOOL)vUsharedimagecache:(NSInteger)THRash;
+ (BOOL)HGinit:(NSInteger)THRash;
+ (BOOL)xWinitwithnamespace:(NSInteger)THRash;
+ (BOOL)LZinitwithnamespacebdiskcachedirectory:(NSInteger)THRash;
+ (BOOL)GGinitwithnamespacerdiskcachedirectoryvconfig:(NSInteger)THRash;
+ (BOOL)oRdealloc:(NSInteger)THRash;
+ (BOOL)UOcachepathforkey:(NSInteger)THRash;
+ (BOOL)TYusercachedirectory:(NSInteger)THRash;
+ (BOOL)QImigratediskcachedirectory:(NSInteger)THRash;
+ (BOOL)DSstoreimagebforkeyncompletion:(NSInteger)THRash;
+ (BOOL)wCstoreimagelforkeyitodiskmcompletion:(NSInteger)THRash;
+ (BOOL)zJstoreimagetimagedatadforkeyftodiskbcompletion:(NSInteger)THRash;
+ (BOOL)oCstoreimagegimagedatauforkeybtomemoryitodiskucompletion:(NSInteger)THRash;
+ (BOOL)KGstoreimagetomemoryhforkey:(NSInteger)THRash;
+ (BOOL)ORstoreimagedatatodiskkforkey:(NSInteger)THRash;
+ (BOOL)FV_Storeimagedatatodiskgforkey:(NSInteger)THRash;
+ (BOOL)WHdiskimageexistswithkeyvcompletion:(NSInteger)THRash;
+ (BOOL)JIdiskimagedataexistswithkey:(NSInteger)THRash;
+ (BOOL)cS_Diskimagedataexistswithkey:(NSInteger)THRash;
+ (BOOL)ELdiskimagedataforkey:(NSInteger)THRash;
+ (BOOL)dXimagefrommemorycacheforkey:(NSInteger)THRash;
+ (BOOL)BTimagefromdiskcacheforkey:(NSInteger)THRash;
+ (BOOL)tRimagefromcacheforkey:(NSInteger)THRash;
+ (BOOL)NZdiskimagedatabysearchingallpathsforkey:(NSInteger)THRash;
+ (BOOL)AWdiskimageforkey:(NSInteger)THRash;
+ (BOOL)WZdiskimageforkeyedata:(NSInteger)THRash;
+ (BOOL)xLdiskimageforkeymdataeoptionsfcontext:(NSInteger)THRash;
+ (BOOL)RBquerycacheoperationforkeymdone:(NSInteger)THRash;
+ (BOOL)vSquerycacheoperationforkeyboptionszdone:(NSInteger)THRash;
+ (BOOL)GLquerycacheoperationforkeyroptionstcontextvdone:(NSInteger)THRash;
+ (BOOL)qEremoveimageforkeyewithcompletion:(NSInteger)THRash;
+ (BOOL)lLremoveimageforkeyufromdiskxwithcompletion:(NSInteger)THRash;
+ (BOOL)HJremoveimageforkeyyfrommemorywfromdiskdwithcompletion:(NSInteger)THRash;
+ (BOOL)dZremoveimagefrommemoryforkey:(NSInteger)THRash;
+ (BOOL)tCremoveimagefromdiskforkey:(NSInteger)THRash;
+ (BOOL)jO_Removeimagefromdiskforkey:(NSInteger)THRash;
+ (BOOL)lVclearmemory:(NSInteger)THRash;
+ (BOOL)iYcleardiskoncompletion:(NSInteger)THRash;
+ (BOOL)cZdeleteoldfileswithcompletionblock:(NSInteger)THRash;
+ (BOOL)iNapplicationwillterminate:(NSInteger)THRash;
+ (BOOL)cFapplicationdidenterbackground:(NSInteger)THRash;
+ (BOOL)DPtotaldisksize:(NSInteger)THRash;
+ (BOOL)cFtotaldiskcount:(NSInteger)THRash;
+ (BOOL)eOcalculatesizewithcompletionblock:(NSInteger)THRash;
+ (BOOL)aCimageoptionsfromcacheoptions:(NSInteger)THRash;

@end
