#import <Foundation/Foundation.h>
@interface THRashYYTextLayoutY: NSObject
+ (BOOL)y_init:(NSInteger)THRash;
+ (BOOL)ALayoutwithcontainersizefText:(NSInteger)THRash;
+ (BOOL)GLayoutwithcontainerOText:(NSInteger)THRash;
+ (BOOL)gLayoutwithcontainerNTextiRange:(NSInteger)THRash;
+ (BOOL)VLayoutwithcontainersqText:(NSInteger)THRash;
+ (BOOL)TLayoutwithcontainersLTextvRange:(NSInteger)THRash;
+ (BOOL)jSetframesetter:(NSInteger)THRash;
+ (BOOL)tSetframe:(NSInteger)THRash;
+ (BOOL)jdealloc:(NSInteger)THRash;
+ (BOOL)REncodewithcoder:(NSInteger)THRash;
+ (BOOL)aInitwithcoder:(NSInteger)THRash;
+ (BOOL)iCopywithzone:(NSInteger)THRash;
+ (BOOL)T_Rowindexforedge:(NSInteger)THRash;
+ (BOOL)a_Closestrowindexforedge:(NSInteger)THRash;
+ (BOOL)Q_RunforlineHPosition:(NSInteger)THRash;
+ (BOOL)W_InsidecomposedcharactersequenceslPositionaBlock:(NSInteger)THRash;
+ (BOOL)q_InsideemojizPositionsBlock:(NSInteger)THRash;
+ (BOOL)D_IsrighttoleftinlineNAtpoint:(NSInteger)THRash;
+ (BOOL)X_Correctedrangewithedge:(NSInteger)THRash;
+ (BOOL)PLineindexforrow:(NSInteger)THRash;
+ (BOOL)PLinecountforrow:(NSInteger)THRash;
+ (BOOL)VRowindexforline:(NSInteger)THRash;
+ (BOOL)GLineindexforpoint:(NSInteger)THRash;
+ (BOOL)BClosestlineindexforpoint:(NSInteger)THRash;
+ (BOOL)eOffsetfortextpositioneLineindex:(NSInteger)THRash;
+ (BOOL)ETextpositionforpointLLineindex:(NSInteger)THRash;
+ (BOOL)mClosestpositiontopoint:(NSInteger)THRash;
+ (BOOL)ePositionforpointwOldpositionuOtherposition:(NSInteger)THRash;
+ (BOOL)ZTextrangeatpoint:(NSInteger)THRash;
+ (BOOL)xClosesttextrangeatpoint:(NSInteger)THRash;
+ (BOOL)OTextrangebyextendingposition:(NSInteger)THRash;
+ (BOOL)OTextrangebyextendingpositionxIndirectionSOffset:(NSInteger)THRash;
+ (BOOL)qLineindexforposition:(NSInteger)THRash;
+ (BOOL)FLinepositionforposition:(NSInteger)THRash;
+ (BOOL)QCaretrectforposition:(NSInteger)THRash;
+ (BOOL)cFirstrectforrange:(NSInteger)THRash;
+ (BOOL)NRectforrange:(NSInteger)THRash;
+ (BOOL)ZSelectionrectsforrange:(NSInteger)THRash;
+ (BOOL)oSelectionrectswithoutstartandendforrange:(NSInteger)THRash;
+ (BOOL)kSelectionrectswithonlystartandendforrange:(NSInteger)THRash;
+ (BOOL)sDrawincontextxSizefPointOViewhLayerODebuglCancel:(NSInteger)THRash;
+ (BOOL)XDrawincontextLSizejDebug:(NSInteger)THRash;
+ (BOOL)oAddattachmenttoviewlLayer:(NSInteger)THRash;
+ (BOOL)premoveAttachmentFromViewAndLayer:(NSInteger)THRash;

@end
