#import <Foundation/Foundation.h>
@interface THRashTHRashMBProgressHUDKf: NSObject
+ (BOOL)oGshowhudaddedtozanimated:(NSInteger)THRash;
+ (BOOL)bZhidehudforviewbanimated:(NSInteger)THRash;
+ (BOOL)SThideallhudsforviewganimated:(NSInteger)THRash;
+ (BOOL)iVhudforview:(NSInteger)THRash;
+ (BOOL)zCallhudsforview:(NSInteger)THRash;
+ (BOOL)oOinitwithframe:(NSInteger)THRash;
+ (BOOL)wAsetblur:(NSInteger)THRash;
+ (BOOL)VJinitwithview:(NSInteger)THRash;
+ (BOOL)pAinitwithwindow:(NSInteger)THRash;
+ (BOOL)rKdealloc:(NSInteger)THRash;
+ (BOOL)yZshow:(NSInteger)THRash;
+ (BOOL)jQhide:(NSInteger)THRash;
+ (BOOL)EShideeafterdelay:(NSInteger)THRash;
+ (BOOL)dDhidedelayed:(NSInteger)THRash;
+ (BOOL)rHhandlegracetimer:(NSInteger)THRash;
+ (BOOL)IUhandleminshowtimer:(NSInteger)THRash;
+ (BOOL)wEdidmovetosuperview:(NSInteger)THRash;
+ (BOOL)HJshowusinganimation:(NSInteger)THRash;
+ (BOOL)XDhideusinganimation:(NSInteger)THRash;
+ (BOOL)tJanimationfinishedofinishedbcontext:(NSInteger)THRash;
+ (BOOL)XSdone:(NSInteger)THRash;
+ (BOOL)eBshowwhileexecutingiontargetdwithobjectfanimated:(NSInteger)THRash;
+ (BOOL)nUshowanimatedtwhileexecutingblock:(NSInteger)THRash;
+ (BOOL)AFshowanimatedswhileexecutingblockgcompletionblock:(NSInteger)THRash;
+ (BOOL)CXshowanimatedpwhileexecutingblockyonqueue:(NSInteger)THRash;
+ (BOOL)IMshowanimatedjwhileexecutingblockuonqueuepcompletionblock:(NSInteger)THRash;
+ (BOOL)HClaunchexecution:(NSInteger)THRash;
+ (BOOL)uHcleanup:(NSInteger)THRash;
+ (BOOL)yAsetuplabels:(NSInteger)THRash;
+ (BOOL)GDupdateindicators:(NSInteger)THRash;
+ (BOOL)MGlayoutsubviews:(NSInteger)THRash;
+ (BOOL)dJdrawrect:(NSInteger)THRash;
+ (BOOL)nUregisterforkvo:(NSInteger)THRash;
+ (BOOL)ZQunregisterfromkvo:(NSInteger)THRash;
+ (BOOL)mGobservablekeypaths:(NSInteger)THRash;
+ (BOOL)yWobservevalueforkeypathdofobjectpchangegcontext:(NSInteger)THRash;
+ (BOOL)FWupdateuiforkeypath:(NSInteger)THRash;
+ (BOOL)QHregisterfornotifications:(NSInteger)THRash;
+ (BOOL)sGunregisterfromnotifications:(NSInteger)THRash;
+ (BOOL)NLdeviceorientationdidchange:(NSInteger)THRash;
+ (BOOL)rNsettransformforcurrentorientation:(NSInteger)THRash;

@end
