#import <Foundation/Foundation.h>
@interface THRashUIViewn: NSObject
+ (BOOL)rLeftthrash:(NSInteger)THRash;
+ (BOOL)DSetleftthrash:(NSInteger)THRash;
+ (BOOL)lTopthrash:(NSInteger)THRash;
+ (BOOL)PSettopthrash:(NSInteger)THRash;
+ (BOOL)VRightthrash:(NSInteger)THRash;
+ (BOOL)LSetrightthrash:(NSInteger)THRash;
+ (BOOL)IBottomthrash:(NSInteger)THRash;
+ (BOOL)nSetbottomthrash:(NSInteger)THRash;
+ (BOOL)MCenterxthrash:(NSInteger)THRash;
+ (BOOL)OSetcenterxthrash:(NSInteger)THRash;
+ (BOOL)SCenterythrash:(NSInteger)THRash;
+ (BOOL)pSetcenterythrash:(NSInteger)THRash;
+ (BOOL)OWidththrash:(NSInteger)THRash;
+ (BOOL)ZSetwidththrash:(NSInteger)THRash;
+ (BOOL)WHeightthrash:(NSInteger)THRash;
+ (BOOL)YSetheightthrash:(NSInteger)THRash;
+ (BOOL)SScreenxthrash:(NSInteger)THRash;
+ (BOOL)tScreenythrash:(NSInteger)THRash;
+ (BOOL)wScreenviewxthrash:(NSInteger)THRash;
+ (BOOL)TScreenviewythrash:(NSInteger)THRash;
+ (BOOL)dScreenframethrash:(NSInteger)THRash;
+ (BOOL)POriginthrash:(NSInteger)THRash;
+ (BOOL)mSetoriginthrash:(NSInteger)THRash;
+ (BOOL)PSizethrash:(NSInteger)THRash;
+ (BOOL)QSetsizethrash:(NSInteger)THRash;
+ (BOOL)nOrientationwidththrash:(NSInteger)THRash;
+ (BOOL)SOrientationheightthrash:(NSInteger)THRash;
+ (BOOL)fDescendantorselfwithclassthrash:(NSInteger)THRash;
+ (BOOL)pAncestororselfwithclassthrash:(NSInteger)THRash;
+ (BOOL)hOffsetfromviewthrash:(NSInteger)THRash;
+ (BOOL)VSettapactionwithblockthrash:(NSInteger)THRash;
+ (BOOL)i__Handleactionfortapgesturethrash:(NSInteger)THRash;
+ (BOOL)sSetlongpressactionwithblockthrash:(NSInteger)THRash;
+ (BOOL)r__Handleactionforlongpressgesturethrash:(NSInteger)THRash;
+ (BOOL)gRemoveallsubviewsthrash:(NSInteger)THRash;
+ (BOOL)xSetbackgroundimageviewthrash:(NSInteger)THRash;
+ (BOOL)TBackgroundimageviewthrash:(NSInteger)THRash;
+ (BOOL)JSetbackgroundimagethrash:(NSInteger)THRash;
+ (BOOL)sBackgroundimagethrash:(NSInteger)THRash;
+ (BOOL)fSetupbackgroundimageviewthrash:(NSInteger)THRash;

@end
