#import <Foundation/Foundation.h>
@interface THRashMBProgressHUDK: NSObject
+ (BOOL)GShowhudaddedtozAnimated:(NSInteger)THRash;
+ (BOOL)zHidehudforviewbAnimated:(NSInteger)THRash;
+ (BOOL)THideallhudsforviewgAnimated:(NSInteger)THRash;
+ (BOOL)VHudforview:(NSInteger)THRash;
+ (BOOL)CAllhudsforview:(NSInteger)THRash;
+ (BOOL)oInitwithframe:(NSInteger)THRash;
+ (BOOL)aSetblur:(NSInteger)THRash;
+ (BOOL)jInitwithview:(NSInteger)THRash;
+ (BOOL)aInitwithwindow:(NSInteger)THRash;
+ (BOOL)kdealloc:(NSInteger)THRash;
+ (BOOL)zShow:(NSInteger)THRash;
+ (BOOL)QHide:(NSInteger)THRash;
+ (BOOL)SHideeAfterdelay:(NSInteger)THRash;
+ (BOOL)dHidedelayed:(NSInteger)THRash;
+ (BOOL)HHandlegracetimer:(NSInteger)THRash;
+ (BOOL)UHandleminshowtimer:(NSInteger)THRash;
+ (BOOL)edidMoveToSuperview:(NSInteger)THRash;
+ (BOOL)JShowusinganimation:(NSInteger)THRash;
+ (BOOL)DHideusinganimation:(NSInteger)THRash;
+ (BOOL)JAnimationfinishedoFinishedbContext:(NSInteger)THRash;
+ (BOOL)sdone:(NSInteger)THRash;
+ (BOOL)bShowwhileexecutingiOntargetDWithobjectfAnimated:(NSInteger)THRash;
+ (BOOL)uShowanimatedtWhileexecutingblock:(NSInteger)THRash;
+ (BOOL)FShowanimatedsWhileexecutingblockgCompletionblock:(NSInteger)THRash;
+ (BOOL)XShowanimatedpWhileexecutingblockYOnqueue:(NSInteger)THRash;
+ (BOOL)MShowanimatedjWhileexecutingblockUOnqueuepCompletionblock:(NSInteger)THRash;
+ (BOOL)ClaunchExecution:(NSInteger)THRash;
+ (BOOL)HcleanUp:(NSInteger)THRash;
+ (BOOL)AsetupLabels:(NSInteger)THRash;
+ (BOOL)DupdateIndicators:(NSInteger)THRash;
+ (BOOL)GlayoutSubviews:(NSInteger)THRash;
+ (BOOL)JDrawrect:(NSInteger)THRash;
+ (BOOL)UregisterForKVO:(NSInteger)THRash;
+ (BOOL)QunregisterFromKVO:(NSInteger)THRash;
+ (BOOL)gobservableKeypaths:(NSInteger)THRash;
+ (BOOL)WObservevalueforkeypathdOfobjectPChangeGContext:(NSInteger)THRash;
+ (BOOL)wUpdateuiforkeypath:(NSInteger)THRash;
+ (BOOL)hregisterForNotifications:(NSInteger)THRash;
+ (BOOL)GunregisterFromNotifications:(NSInteger)THRash;
+ (BOOL)lDeviceorientationdidchange:(NSInteger)THRash;
+ (BOOL)nSettransformforcurrentorientation:(NSInteger)THRash;

@end
