#import <Foundation/Foundation.h>
@interface THRashTHRashMBProgressHUDAu: NSObject
+ (BOOL)fJshowhudaddedtoanimatedthrash:(NSInteger)THRash;
+ (BOOL)mHhidehudforviewanimatedthrash:(NSInteger)THRash;
+ (BOOL)HHhideallhudsforviewanimatedthrash:(NSInteger)THRash;
+ (BOOL)nShudforviewthrash:(NSInteger)THRash;
+ (BOOL)FTallhudsforviewthrash:(NSInteger)THRash;
+ (BOOL)iIinitwithframethrash:(NSInteger)THRash;
+ (BOOL)KYsetblurthrash:(NSInteger)THRash;
+ (BOOL)WAinitwithviewthrash:(NSInteger)THRash;
+ (BOOL)cAinitwithwindowthrash:(NSInteger)THRash;
+ (BOOL)TZdeallocthrash:(NSInteger)THRash;
+ (BOOL)YWshowthrash:(NSInteger)THRash;
+ (BOOL)gKhidethrash:(NSInteger)THRash;
+ (BOOL)IFhideafterdelaythrash:(NSInteger)THRash;
+ (BOOL)lKhidedelayedthrash:(NSInteger)THRash;
+ (BOOL)NOhandlegracetimerthrash:(NSInteger)THRash;
+ (BOOL)bPhandleminshowtimerthrash:(NSInteger)THRash;
+ (BOOL)gXdidmovetosuperviewthrash:(NSInteger)THRash;
+ (BOOL)WKshowusinganimationthrash:(NSInteger)THRash;
+ (BOOL)VThideusinganimationthrash:(NSInteger)THRash;
+ (BOOL)uHanimationfinishedfinishedcontextthrash:(NSInteger)THRash;
+ (BOOL)ITdonethrash:(NSInteger)THRash;
+ (BOOL)kCshowwhileexecutingontargetwithobjectanimatedthrash:(NSInteger)THRash;
+ (BOOL)zFshowanimatedwhileexecutingblockthrash:(NSInteger)THRash;
+ (BOOL)GAshowanimatedwhileexecutingblockcompletionblockthrash:(NSInteger)THRash;
+ (BOOL)BLshowanimatedwhileexecutingblockonqueuethrash:(NSInteger)THRash;
+ (BOOL)IBshowanimatedwhileexecutingblockonqueuecompletionblockthrash:(NSInteger)THRash;
+ (BOOL)kOlaunchexecutionthrash:(NSInteger)THRash;
+ (BOOL)lIcleanupthrash:(NSInteger)THRash;
+ (BOOL)XVsetuplabelsthrash:(NSInteger)THRash;
+ (BOOL)NLupdateindicatorsthrash:(NSInteger)THRash;
+ (BOOL)ZFlayoutsubviewsthrash:(NSInteger)THRash;
+ (BOOL)AJdrawrectthrash:(NSInteger)THRash;
+ (BOOL)jNregisterforkvothrash:(NSInteger)THRash;
+ (BOOL)fUunregisterfromkvothrash:(NSInteger)THRash;
+ (BOOL)UNobservablekeypathsthrash:(NSInteger)THRash;
+ (BOOL)DHobservevalueforkeypathofobjectchangecontextthrash:(NSInteger)THRash;
+ (BOOL)cPupdateuiforkeypaththrash:(NSInteger)THRash;
+ (BOOL)SJregisterfornotificationsthrash:(NSInteger)THRash;
+ (BOOL)xVunregisterfromnotificationsthrash:(NSInteger)THRash;
+ (BOOL)GQdeviceorientationdidchangethrash:(NSInteger)THRash;
+ (BOOL)NPsettransformforcurrentorientationthrash:(NSInteger)THRash;

@end
