#import <Foundation/Foundation.h>
@interface THRashYYTextLayoutZ: NSObject
+ (BOOL)m_Initthrash:(NSInteger)THRash;
+ (BOOL)oLayoutwithcontainersizetextthrash:(NSInteger)THRash;
+ (BOOL)PLayoutwithcontainertextthrash:(NSInteger)THRash;
+ (BOOL)cLayoutwithcontainertextrangethrash:(NSInteger)THRash;
+ (BOOL)yLayoutwithcontainerstextthrash:(NSInteger)THRash;
+ (BOOL)fLayoutwithcontainerstextrangethrash:(NSInteger)THRash;
+ (BOOL)GSetframesetterthrash:(NSInteger)THRash;
+ (BOOL)CSetframethrash:(NSInteger)THRash;
+ (BOOL)WDeallocthrash:(NSInteger)THRash;
+ (BOOL)uEncodewithcoderthrash:(NSInteger)THRash;
+ (BOOL)xInitwithcoderthrash:(NSInteger)THRash;
+ (BOOL)oCopywithzonethrash:(NSInteger)THRash;
+ (BOOL)q_Rowindexforedgethrash:(NSInteger)THRash;
+ (BOOL)R_Closestrowindexforedgethrash:(NSInteger)THRash;
+ (BOOL)G_Runforlinepositionthrash:(NSInteger)THRash;
+ (BOOL)n_Insidecomposedcharactersequencespositionblockthrash:(NSInteger)THRash;
+ (BOOL)d_Insideemojipositionblockthrash:(NSInteger)THRash;
+ (BOOL)D_Isrighttoleftinlineatpointthrash:(NSInteger)THRash;
+ (BOOL)Y_Correctedrangewithedgethrash:(NSInteger)THRash;
+ (BOOL)zLineindexforrowthrash:(NSInteger)THRash;
+ (BOOL)gLinecountforrowthrash:(NSInteger)THRash;
+ (BOOL)NRowindexforlinethrash:(NSInteger)THRash;
+ (BOOL)cLineindexforpointthrash:(NSInteger)THRash;
+ (BOOL)zClosestlineindexforpointthrash:(NSInteger)THRash;
+ (BOOL)qOffsetfortextpositionlineindexthrash:(NSInteger)THRash;
+ (BOOL)oTextpositionforpointlineindexthrash:(NSInteger)THRash;
+ (BOOL)CClosestpositiontopointthrash:(NSInteger)THRash;
+ (BOOL)kPositionforpointoldpositionotherpositionthrash:(NSInteger)THRash;
+ (BOOL)HTextrangeatpointthrash:(NSInteger)THRash;
+ (BOOL)iClosesttextrangeatpointthrash:(NSInteger)THRash;
+ (BOOL)rTextrangebyextendingpositionthrash:(NSInteger)THRash;
+ (BOOL)oTextrangebyextendingpositionindirectionoffsetthrash:(NSInteger)THRash;
+ (BOOL)MLineindexforpositionthrash:(NSInteger)THRash;
+ (BOOL)SLinepositionforpositionthrash:(NSInteger)THRash;
+ (BOOL)ACaretrectforpositionthrash:(NSInteger)THRash;
+ (BOOL)YFirstrectforrangethrash:(NSInteger)THRash;
+ (BOOL)sRectforrangethrash:(NSInteger)THRash;
+ (BOOL)wSelectionrectsforrangethrash:(NSInteger)THRash;
+ (BOOL)rSelectionrectswithoutstartandendforrangethrash:(NSInteger)THRash;
+ (BOOL)WSelectionrectswithonlystartandendforrangethrash:(NSInteger)THRash;
+ (BOOL)WDrawincontextsizepointviewlayerdebugcancelthrash:(NSInteger)THRash;
+ (BOOL)wDrawincontextsizedebugthrash:(NSInteger)THRash;
+ (BOOL)UAddattachmenttoviewlayerthrash:(NSInteger)THRash;
+ (BOOL)vRemoveattachmentfromviewandlayerthrash:(NSInteger)THRash;

@end
