#import <Foundation/Foundation.h>
@interface THRashTHRashYYTextLayoutYX: NSObject
+ (BOOL)YY_Init:(NSInteger)THRash;
+ (BOOL)RAlayoutwithcontainersizeftext:(NSInteger)THRash;
+ (BOOL)QGlayoutwithcontainerotext:(NSInteger)THRash;
+ (BOOL)gGlayoutwithcontainerntextirange:(NSInteger)THRash;
+ (BOOL)FVlayoutwithcontainersqtext:(NSInteger)THRash;
+ (BOOL)yTlayoutwithcontainersltextvrange:(NSInteger)THRash;
+ (BOOL)uJsetframesetter:(NSInteger)THRash;
+ (BOOL)NTsetframe:(NSInteger)THRash;
+ (BOOL)TJdealloc:(NSInteger)THRash;
+ (BOOL)NRencodewithcoder:(NSInteger)THRash;
+ (BOOL)sAinitwithcoder:(NSInteger)THRash;
+ (BOOL)PIcopywithzone:(NSInteger)THRash;
+ (BOOL)jT_Rowindexforedge:(NSInteger)THRash;
+ (BOOL)AA_Closestrowindexforedge:(NSInteger)THRash;
+ (BOOL)fQ_Runforlinehposition:(NSInteger)THRash;
+ (BOOL)jW_Insidecomposedcharactersequenceslpositionablock:(NSInteger)THRash;
+ (BOOL)hQ_Insideemojizpositionsblock:(NSInteger)THRash;
+ (BOOL)sD_Isrighttoleftinlinenatpoint:(NSInteger)THRash;
+ (BOOL)GX_Correctedrangewithedge:(NSInteger)THRash;
+ (BOOL)xPlineindexforrow:(NSInteger)THRash;
+ (BOOL)vPlinecountforrow:(NSInteger)THRash;
+ (BOOL)UVrowindexforline:(NSInteger)THRash;
+ (BOOL)iGlineindexforpoint:(NSInteger)THRash;
+ (BOOL)JBclosestlineindexforpoint:(NSInteger)THRash;
+ (BOOL)gEoffsetfortextpositionelineindex:(NSInteger)THRash;
+ (BOOL)cEtextpositionforpointllineindex:(NSInteger)THRash;
+ (BOOL)cMclosestpositiontopoint:(NSInteger)THRash;
+ (BOOL)pEpositionforpointwoldpositionuotherposition:(NSInteger)THRash;
+ (BOOL)sZtextrangeatpoint:(NSInteger)THRash;
+ (BOOL)XXclosesttextrangeatpoint:(NSInteger)THRash;
+ (BOOL)hOtextrangebyextendingposition:(NSInteger)THRash;
+ (BOOL)ROtextrangebyextendingpositionxindirectionsoffset:(NSInteger)THRash;
+ (BOOL)LQlineindexforposition:(NSInteger)THRash;
+ (BOOL)OFlinepositionforposition:(NSInteger)THRash;
+ (BOOL)IQcaretrectforposition:(NSInteger)THRash;
+ (BOOL)dCfirstrectforrange:(NSInteger)THRash;
+ (BOOL)KNrectforrange:(NSInteger)THRash;
+ (BOOL)SZselectionrectsforrange:(NSInteger)THRash;
+ (BOOL)YOselectionrectswithoutstartandendforrange:(NSInteger)THRash;
+ (BOOL)aKselectionrectswithonlystartandendforrange:(NSInteger)THRash;
+ (BOOL)rSdrawincontextxsizefpointoviewhlayerodebuglcancel:(NSInteger)THRash;
+ (BOOL)HXdrawincontextlsizejdebug:(NSInteger)THRash;
+ (BOOL)GOaddattachmenttoviewllayer:(NSInteger)THRash;
+ (BOOL)SPremoveattachmentfromviewandlayer:(NSInteger)THRash;

@end
