#import <Foundation/Foundation.h>
@interface THRashTHRashYYDiskCachemL: NSObject
+ (BOOL)WE_Trimrecursivelythrash:(NSInteger)THRash;
+ (BOOL)jA_Triminbackgroundthrash:(NSInteger)THRash;
+ (BOOL)zL_Trimtocostthrash:(NSInteger)THRash;
+ (BOOL)lL_Trimtocountthrash:(NSInteger)THRash;
+ (BOOL)rA_Trimtoagethrash:(NSInteger)THRash;
+ (BOOL)OC_Trimtofreediskspacethrash:(NSInteger)THRash;
+ (BOOL)kE_Filenameforkeythrash:(NSInteger)THRash;
+ (BOOL)iK_Appwillbeterminatedthrash:(NSInteger)THRash;
+ (BOOL)RMdeallocthrash:(NSInteger)THRash;
+ (BOOL)KYinitthrash:(NSInteger)THRash;
+ (BOOL)IQinitwithpaththrash:(NSInteger)THRash;
+ (BOOL)bPinitwithpathinlinethresholdthrash:(NSInteger)THRash;
+ (BOOL)xCcontainsobjectforkeythrash:(NSInteger)THRash;
+ (BOOL)XOcontainsobjectforkeywithblockthrash:(NSInteger)THRash;
+ (BOOL)vHobjectforkeythrash:(NSInteger)THRash;
+ (BOOL)aDobjectforkeywithblockthrash:(NSInteger)THRash;
+ (BOOL)DEsetobjectforkeythrash:(NSInteger)THRash;
+ (BOOL)wBsetobjectforkeywithblockthrash:(NSInteger)THRash;
+ (BOOL)tOremoveobjectforkeythrash:(NSInteger)THRash;
+ (BOOL)qJremoveobjectforkeywithblockthrash:(NSInteger)THRash;
+ (BOOL)BNremoveallobjectsthrash:(NSInteger)THRash;
+ (BOOL)qUremoveallobjectswithblockthrash:(NSInteger)THRash;
+ (BOOL)wDremoveallobjectswithprogressblockendblockthrash:(NSInteger)THRash;
+ (BOOL)kJtotalcountthrash:(NSInteger)THRash;
+ (BOOL)fZtotalcountwithblockthrash:(NSInteger)THRash;
+ (BOOL)VZtotalcostthrash:(NSInteger)THRash;
+ (BOOL)gBtotalcostwithblockthrash:(NSInteger)THRash;
+ (BOOL)QGtrimtocountthrash:(NSInteger)THRash;
+ (BOOL)INtrimtocountwithblockthrash:(NSInteger)THRash;
+ (BOOL)BFtrimtocostthrash:(NSInteger)THRash;
+ (BOOL)tItrimtocostwithblockthrash:(NSInteger)THRash;
+ (BOOL)FUtrimtoagethrash:(NSInteger)THRash;
+ (BOOL)fYtrimtoagewithblockthrash:(NSInteger)THRash;
+ (BOOL)FCgetextendeddatafromobjectthrash:(NSInteger)THRash;
+ (BOOL)OKsetextendeddatatoobjectthrash:(NSInteger)THRash;
+ (BOOL)YZdescriptionthrash:(NSInteger)THRash;
+ (BOOL)rMerrorlogsenabledthrash:(NSInteger)THRash;
+ (BOOL)kUseterrorlogsenabledthrash:(NSInteger)THRash;

@end
