#import <Foundation/Foundation.h>
@interface THRashTHRashUIViewxQ: NSObject
+ (BOOL)XJleft:(NSInteger)THRash;
+ (BOOL)dNsetleft:(NSInteger)THRash;
+ (BOOL)lTtop:(NSInteger)THRash;
+ (BOOL)AUsettop:(NSInteger)THRash;
+ (BOOL)uUright:(NSInteger)THRash;
+ (BOOL)HNsetright:(NSInteger)THRash;
+ (BOOL)tHbottom:(NSInteger)THRash;
+ (BOOL)HFsetbottom:(NSInteger)THRash;
+ (BOOL)MGcenterx:(NSInteger)THRash;
+ (BOOL)mOsetcenterx:(NSInteger)THRash;
+ (BOOL)cTcentery:(NSInteger)THRash;
+ (BOOL)QEsetcentery:(NSInteger)THRash;
+ (BOOL)LRwidth:(NSInteger)THRash;
+ (BOOL)oGsetwidth:(NSInteger)THRash;
+ (BOOL)aXheight:(NSInteger)THRash;
+ (BOOL)VZsetheight:(NSInteger)THRash;
+ (BOOL)zGscreenx:(NSInteger)THRash;
+ (BOOL)oYscreeny:(NSInteger)THRash;
+ (BOOL)uYscreenviewx:(NSInteger)THRash;
+ (BOOL)ULscreenviewy:(NSInteger)THRash;
+ (BOOL)CVscreenframe:(NSInteger)THRash;
+ (BOOL)ZMorigin:(NSInteger)THRash;
+ (BOOL)BFsetorigin:(NSInteger)THRash;
+ (BOOL)FYsize:(NSInteger)THRash;
+ (BOOL)THsetsize:(NSInteger)THRash;
+ (BOOL)LRorientationwidth:(NSInteger)THRash;
+ (BOOL)wRorientationheight:(NSInteger)THRash;
+ (BOOL)AOdescendantorselfwithclass:(NSInteger)THRash;
+ (BOOL)SQancestororselfwithclass:(NSInteger)THRash;
+ (BOOL)xNoffsetfromview:(NSInteger)THRash;
+ (BOOL)UOsettapactionwithblock:(NSInteger)THRash;
+ (BOOL)gQ__Handleactionfortapgesture:(NSInteger)THRash;
+ (BOOL)TBsetlongpressactionwithblock:(NSInteger)THRash;
+ (BOOL)IB__Handleactionforlongpressgesture:(NSInteger)THRash;
+ (BOOL)VKremoveallsubviews:(NSInteger)THRash;
+ (BOOL)uDsetbackgroundimageview:(NSInteger)THRash;
+ (BOOL)bTbackgroundimageview:(NSInteger)THRash;
+ (BOOL)eQsetbackgroundimage:(NSInteger)THRash;
+ (BOOL)ATbackgroundimage:(NSInteger)THRash;
+ (BOOL)lSsetupbackgroundimageview:(NSInteger)THRash;

@end
