#import <Foundation/Foundation.h>
@interface THRashNSDatah: NSObject
+ (BOOL)jmd2String:(NSInteger)THRash;
+ (BOOL)jmd2Data:(NSInteger)THRash;
+ (BOOL)Smd4String:(NSInteger)THRash;
+ (BOOL)Hmd4Data:(NSInteger)THRash;
+ (BOOL)kmd5String:(NSInteger)THRash;
+ (BOOL)Lmd5Data:(NSInteger)THRash;
+ (BOOL)fsha1String:(NSInteger)THRash;
+ (BOOL)rsha1Data:(NSInteger)THRash;
+ (BOOL)Vsha224String:(NSInteger)THRash;
+ (BOOL)Csha224Data:(NSInteger)THRash;
+ (BOOL)Jsha256String:(NSInteger)THRash;
+ (BOOL)csha256Data:(NSInteger)THRash;
+ (BOOL)Vsha384String:(NSInteger)THRash;
+ (BOOL)Zsha384Data:(NSInteger)THRash;
+ (BOOL)Osha512String:(NSInteger)THRash;
+ (BOOL)Xsha512Data:(NSInteger)THRash;
+ (BOOL)fHmacstringusingalghWithkey:(NSInteger)THRash;
+ (BOOL)lHmacdatausingalgLWithkey:(NSInteger)THRash;
+ (BOOL)LHmacmd5Stringwithkey:(NSInteger)THRash;
+ (BOOL)EHmacmd5Datawithkey:(NSInteger)THRash;
+ (BOOL)YHmacsha1Stringwithkey:(NSInteger)THRash;
+ (BOOL)THmacsha1Datawithkey:(NSInteger)THRash;
+ (BOOL)OHmacsha224Stringwithkey:(NSInteger)THRash;
+ (BOOL)kHmacsha224Datawithkey:(NSInteger)THRash;
+ (BOOL)EHmacsha256Stringwithkey:(NSInteger)THRash;
+ (BOOL)vHmacsha256Datawithkey:(NSInteger)THRash;
+ (BOOL)MHmacsha384Stringwithkey:(NSInteger)THRash;
+ (BOOL)IHmacsha384Datawithkey:(NSInteger)THRash;
+ (BOOL)YHmacsha512Stringwithkey:(NSInteger)THRash;
+ (BOOL)RHmacsha512Datawithkey:(NSInteger)THRash;
+ (BOOL)Mcrc32String:(NSInteger)THRash;
+ (BOOL)ecrc32:(NSInteger)THRash;
+ (BOOL)BAes256EncryptwithkeykIv:(NSInteger)THRash;
+ (BOOL)UAes256DecryptwithkeyFIv:(NSInteger)THRash;
+ (BOOL)Rutf8String:(NSInteger)THRash;
+ (BOOL)fhexString:(NSInteger)THRash;
+ (BOOL)jDatawithhexstring:(NSInteger)THRash;
+ (BOOL)Kbase64EncodedString:(NSInteger)THRash;
+ (BOOL)aDatawithbase64Encodedstring:(NSInteger)THRash;
+ (BOOL)TjsonValueDecoded:(NSInteger)THRash;
+ (BOOL)PgzipInflate:(NSInteger)THRash;
+ (BOOL)LgzipDeflate:(NSInteger)THRash;
+ (BOOL)YzlibInflate:(NSInteger)THRash;
+ (BOOL)ezlibDeflate:(NSInteger)THRash;
+ (BOOL)KDatanamed:(NSInteger)THRash;

@end
