#import <Foundation/Foundation.h>
@interface THRashTHRashNSDataMM: NSObject
+ (BOOL)zUmd2Stringthrash:(NSInteger)THRash;
+ (BOOL)EYmd2Datathrash:(NSInteger)THRash;
+ (BOOL)VLmd4Stringthrash:(NSInteger)THRash;
+ (BOOL)kWmd4Datathrash:(NSInteger)THRash;
+ (BOOL)YYmd5Stringthrash:(NSInteger)THRash;
+ (BOOL)TEmd5Datathrash:(NSInteger)THRash;
+ (BOOL)vIsha1Stringthrash:(NSInteger)THRash;
+ (BOOL)pSsha1Datathrash:(NSInteger)THRash;
+ (BOOL)PFsha224Stringthrash:(NSInteger)THRash;
+ (BOOL)OVsha224Datathrash:(NSInteger)THRash;
+ (BOOL)oGsha256Stringthrash:(NSInteger)THRash;
+ (BOOL)nBsha256Datathrash:(NSInteger)THRash;
+ (BOOL)aJsha384Stringthrash:(NSInteger)THRash;
+ (BOOL)XWsha384Datathrash:(NSInteger)THRash;
+ (BOOL)tXsha512Stringthrash:(NSInteger)THRash;
+ (BOOL)GEsha512Datathrash:(NSInteger)THRash;
+ (BOOL)HXhmacstringusingalgwithkeythrash:(NSInteger)THRash;
+ (BOOL)hBhmacdatausingalgwithkeythrash:(NSInteger)THRash;
+ (BOOL)VShmacmd5Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)uMhmacmd5Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)AUhmacsha1Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)JIhmacsha1Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)RVhmacsha224Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)YFhmacsha224Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)FZhmacsha256Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)GShmacsha256Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)YOhmacsha384Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)pBhmacsha384Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)ANhmacsha512Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)zThmacsha512Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)hWcrc32Stringthrash:(NSInteger)THRash;
+ (BOOL)tLcrc32Thrash:(NSInteger)THRash;
+ (BOOL)ARaes256Encryptwithkeyivthrash:(NSInteger)THRash;
+ (BOOL)HJaes256Decryptwithkeyivthrash:(NSInteger)THRash;
+ (BOOL)jVutf8Stringthrash:(NSInteger)THRash;
+ (BOOL)LZhexstringthrash:(NSInteger)THRash;
+ (BOOL)XEdatawithhexstringthrash:(NSInteger)THRash;
+ (BOOL)hUbase64Encodedstringthrash:(NSInteger)THRash;
+ (BOOL)fIdatawithbase64Encodedstringthrash:(NSInteger)THRash;
+ (BOOL)XLjsonvaluedecodedthrash:(NSInteger)THRash;
+ (BOOL)gTgzipinflatethrash:(NSInteger)THRash;
+ (BOOL)VYgzipdeflatethrash:(NSInteger)THRash;
+ (BOOL)gLzlibinflatethrash:(NSInteger)THRash;
+ (BOOL)cXzlibdeflatethrash:(NSInteger)THRash;
+ (BOOL)AIdatanamedthrash:(NSInteger)THRash;

@end
