#import <Foundation/Foundation.h>
@interface THRashTHRashYYTextLayoutZT: NSObject
+ (BOOL)nM_Initthrash:(NSInteger)THRash;
+ (BOOL)xOlayoutwithcontainersizetextthrash:(NSInteger)THRash;
+ (BOOL)DPlayoutwithcontainertextthrash:(NSInteger)THRash;
+ (BOOL)QClayoutwithcontainertextrangethrash:(NSInteger)THRash;
+ (BOOL)eYlayoutwithcontainerstextthrash:(NSInteger)THRash;
+ (BOOL)IFlayoutwithcontainerstextrangethrash:(NSInteger)THRash;
+ (BOOL)IGsetframesetterthrash:(NSInteger)THRash;
+ (BOOL)zCsetframethrash:(NSInteger)THRash;
+ (BOOL)bWdeallocthrash:(NSInteger)THRash;
+ (BOOL)SUencodewithcoderthrash:(NSInteger)THRash;
+ (BOOL)rXinitwithcoderthrash:(NSInteger)THRash;
+ (BOOL)fOcopywithzonethrash:(NSInteger)THRash;
+ (BOOL)CQ_Rowindexforedgethrash:(NSInteger)THRash;
+ (BOOL)KR_Closestrowindexforedgethrash:(NSInteger)THRash;
+ (BOOL)nG_Runforlinepositionthrash:(NSInteger)THRash;
+ (BOOL)HN_Insidecomposedcharactersequencespositionblockthrash:(NSInteger)THRash;
+ (BOOL)vD_Insideemojipositionblockthrash:(NSInteger)THRash;
+ (BOOL)iD_Isrighttoleftinlineatpointthrash:(NSInteger)THRash;
+ (BOOL)DY_Correctedrangewithedgethrash:(NSInteger)THRash;
+ (BOOL)SZlineindexforrowthrash:(NSInteger)THRash;
+ (BOOL)WGlinecountforrowthrash:(NSInteger)THRash;
+ (BOOL)YNrowindexforlinethrash:(NSInteger)THRash;
+ (BOOL)ZClineindexforpointthrash:(NSInteger)THRash;
+ (BOOL)aZclosestlineindexforpointthrash:(NSInteger)THRash;
+ (BOOL)uQoffsetfortextpositionlineindexthrash:(NSInteger)THRash;
+ (BOOL)vOtextpositionforpointlineindexthrash:(NSInteger)THRash;
+ (BOOL)WCclosestpositiontopointthrash:(NSInteger)THRash;
+ (BOOL)EKpositionforpointoldpositionotherpositionthrash:(NSInteger)THRash;
+ (BOOL)bHtextrangeatpointthrash:(NSInteger)THRash;
+ (BOOL)SIclosesttextrangeatpointthrash:(NSInteger)THRash;
+ (BOOL)bRtextrangebyextendingpositionthrash:(NSInteger)THRash;
+ (BOOL)ZOtextrangebyextendingpositionindirectionoffsetthrash:(NSInteger)THRash;
+ (BOOL)MMlineindexforpositionthrash:(NSInteger)THRash;
+ (BOOL)nSlinepositionforpositionthrash:(NSInteger)THRash;
+ (BOOL)pAcaretrectforpositionthrash:(NSInteger)THRash;
+ (BOOL)IYfirstrectforrangethrash:(NSInteger)THRash;
+ (BOOL)lSrectforrangethrash:(NSInteger)THRash;
+ (BOOL)IWselectionrectsforrangethrash:(NSInteger)THRash;
+ (BOOL)KRselectionrectswithoutstartandendforrangethrash:(NSInteger)THRash;
+ (BOOL)NWselectionrectswithonlystartandendforrangethrash:(NSInteger)THRash;
+ (BOOL)LWdrawincontextsizepointviewlayerdebugcancelthrash:(NSInteger)THRash;
+ (BOOL)CWdrawincontextsizedebugthrash:(NSInteger)THRash;
+ (BOOL)tUaddattachmenttoviewlayerthrash:(NSInteger)THRash;
+ (BOOL)WVremoveattachmentfromviewandlayerthrash:(NSInteger)THRash;

@end
