#import <Foundation/Foundation.h>
@interface THRashNSDataM: NSObject
+ (BOOL)uMd2Stringthrash:(NSInteger)THRash;
+ (BOOL)YMd2Datathrash:(NSInteger)THRash;
+ (BOOL)LMd4Stringthrash:(NSInteger)THRash;
+ (BOOL)WMd4Datathrash:(NSInteger)THRash;
+ (BOOL)yMd5Stringthrash:(NSInteger)THRash;
+ (BOOL)eMd5Datathrash:(NSInteger)THRash;
+ (BOOL)ISha1Stringthrash:(NSInteger)THRash;
+ (BOOL)SSha1Datathrash:(NSInteger)THRash;
+ (BOOL)FSha224Stringthrash:(NSInteger)THRash;
+ (BOOL)VSha224Datathrash:(NSInteger)THRash;
+ (BOOL)gSha256Stringthrash:(NSInteger)THRash;
+ (BOOL)BSha256Datathrash:(NSInteger)THRash;
+ (BOOL)jSha384Stringthrash:(NSInteger)THRash;
+ (BOOL)wSha384Datathrash:(NSInteger)THRash;
+ (BOOL)XSha512Stringthrash:(NSInteger)THRash;
+ (BOOL)eSha512Datathrash:(NSInteger)THRash;
+ (BOOL)xHmacstringusingalgwithkeythrash:(NSInteger)THRash;
+ (BOOL)BHmacdatausingalgwithkeythrash:(NSInteger)THRash;
+ (BOOL)sHmacmd5Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)mHmacmd5Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)uHmacsha1Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)IHmacsha1Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)vHmacsha224Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)FHmacsha224Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)zHmacsha256Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)SHmacsha256Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)oHmacsha384Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)BHmacsha384Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)nHmacsha512Stringwithkeythrash:(NSInteger)THRash;
+ (BOOL)THmacsha512Datawithkeythrash:(NSInteger)THRash;
+ (BOOL)WCrc32Stringthrash:(NSInteger)THRash;
+ (BOOL)LCrc32Thrash:(NSInteger)THRash;
+ (BOOL)RAes256Encryptwithkeyivthrash:(NSInteger)THRash;
+ (BOOL)JAes256Decryptwithkeyivthrash:(NSInteger)THRash;
+ (BOOL)VUtf8Stringthrash:(NSInteger)THRash;
+ (BOOL)ZHexstringthrash:(NSInteger)THRash;
+ (BOOL)eDatawithhexstringthrash:(NSInteger)THRash;
+ (BOOL)UBase64Encodedstringthrash:(NSInteger)THRash;
+ (BOOL)IDatawithbase64Encodedstringthrash:(NSInteger)THRash;
+ (BOOL)lJsonvaluedecodedthrash:(NSInteger)THRash;
+ (BOOL)tGzipinflatethrash:(NSInteger)THRash;
+ (BOOL)YGzipdeflatethrash:(NSInteger)THRash;
+ (BOOL)LZlibinflatethrash:(NSInteger)THRash;
+ (BOOL)XZlibdeflatethrash:(NSInteger)THRash;
+ (BOOL)IDatanamedthrash:(NSInteger)THRash;

@end
