#import <Foundation/Foundation.h>
@interface THRashSDImageCacheK: NSObject
+ (BOOL)usharedImageCache:(NSInteger)THRash;
+ (BOOL)ginit:(NSInteger)THRash;
+ (BOOL)wInitwithnamespace:(NSInteger)THRash;
+ (BOOL)ZInitwithnamespacebDiskcachedirectory:(NSInteger)THRash;
+ (BOOL)GInitwithnamespacerDiskcachedirectoryvConfig:(NSInteger)THRash;
+ (BOOL)Rdealloc:(NSInteger)THRash;
+ (BOOL)oCachepathforkey:(NSInteger)THRash;
+ (BOOL)YuserCacheDirectory:(NSInteger)THRash;
+ (BOOL)imigrateDiskCacheDirectory:(NSInteger)THRash;
+ (BOOL)sStoreimagebForkeynCompletion:(NSInteger)THRash;
+ (BOOL)CStoreimageLForkeyiTodiskMCompletion:(NSInteger)THRash;
+ (BOOL)jStoreimagetImagedataDForkeyfTodiskBCompletion:(NSInteger)THRash;
+ (BOOL)CStoreimageGImagedatauForkeyBTomemoryiTodiskuCompletion:(NSInteger)THRash;
+ (BOOL)GStoreimagetomemoryhForkey:(NSInteger)THRash;
+ (BOOL)rStoreimagedatatodiskkForkey:(NSInteger)THRash;
+ (BOOL)v_StoreimagedatatodiskgForkey:(NSInteger)THRash;
+ (BOOL)HDiskimageexistswithkeyVCompletion:(NSInteger)THRash;
+ (BOOL)IDiskimagedataexistswithkey:(NSInteger)THRash;
+ (BOOL)s_Diskimagedataexistswithkey:(NSInteger)THRash;
+ (BOOL)LDiskimagedataforkey:(NSInteger)THRash;
+ (BOOL)xImagefrommemorycacheforkey:(NSInteger)THRash;
+ (BOOL)tImagefromdiskcacheforkey:(NSInteger)THRash;
+ (BOOL)RImagefromcacheforkey:(NSInteger)THRash;
+ (BOOL)ZDiskimagedatabysearchingallpathsforkey:(NSInteger)THRash;
+ (BOOL)wDiskimageforkey:(NSInteger)THRash;
+ (BOOL)zDiskimageforkeyeData:(NSInteger)THRash;
+ (BOOL)LDiskimageforkeyMDataEOptionsFContext:(NSInteger)THRash;
+ (BOOL)bQuerycacheoperationforkeymDone:(NSInteger)THRash;
+ (BOOL)sQuerycacheoperationforkeyBOptionsZDone:(NSInteger)THRash;
+ (BOOL)LQuerycacheoperationforkeyrOptionsTContextVDone:(NSInteger)THRash;
+ (BOOL)ERemoveimageforkeyEWithcompletion:(NSInteger)THRash;
+ (BOOL)lRemoveimageforkeyUFromdiskxWithcompletion:(NSInteger)THRash;
+ (BOOL)JRemoveimageforkeyyFrommemoryWFromdiskdWithcompletion:(NSInteger)THRash;
+ (BOOL)ZRemoveimagefrommemoryforkey:(NSInteger)THRash;
+ (BOOL)CRemoveimagefromdiskforkey:(NSInteger)THRash;
+ (BOOL)O_Removeimagefromdiskforkey:(NSInteger)THRash;
+ (BOOL)VclearMemory:(NSInteger)THRash;
+ (BOOL)YCleardiskoncompletion:(NSInteger)THRash;
+ (BOOL)ZDeleteoldfileswithcompletionblock:(NSInteger)THRash;
+ (BOOL)nApplicationwillterminate:(NSInteger)THRash;
+ (BOOL)FApplicationdidenterbackground:(NSInteger)THRash;
+ (BOOL)ptotalDiskSize:(NSInteger)THRash;
+ (BOOL)ftotalDiskCount:(NSInteger)THRash;
+ (BOOL)oCalculatesizewithcompletionblock:(NSInteger)THRash;
+ (BOOL)CImageoptionsfromcacheoptions:(NSInteger)THRash;

@end
