#import <Foundation/Foundation.h>
@interface THRashSDImageCacheV: NSObject
+ (BOOL)XSharedimagecachethrash:(NSInteger)THRash;
+ (BOOL)dInitthrash:(NSInteger)THRash;
+ (BOOL)xInitwithnamespacethrash:(NSInteger)THRash;
+ (BOOL)jInitwithnamespacediskcachedirectorythrash:(NSInteger)THRash;
+ (BOOL)kInitwithnamespacediskcachedirectoryconfigthrash:(NSInteger)THRash;
+ (BOOL)kDeallocthrash:(NSInteger)THRash;
+ (BOOL)ACachepathforkeythrash:(NSInteger)THRash;
+ (BOOL)HUsercachedirectorythrash:(NSInteger)THRash;
+ (BOOL)tMigratediskcachedirectorythrash:(NSInteger)THRash;
+ (BOOL)kStoreimageforkeycompletionthrash:(NSInteger)THRash;
+ (BOOL)CStoreimageforkeytodiskcompletionthrash:(NSInteger)THRash;
+ (BOOL)MStoreimageimagedataforkeytodiskcompletionthrash:(NSInteger)THRash;
+ (BOOL)KStoreimageimagedataforkeytomemorytodiskcompletionthrash:(NSInteger)THRash;
+ (BOOL)oStoreimagetomemoryforkeythrash:(NSInteger)THRash;
+ (BOOL)bStoreimagedatatodiskforkeythrash:(NSInteger)THRash;
+ (BOOL)q_Storeimagedatatodiskforkeythrash:(NSInteger)THRash;
+ (BOOL)kDiskimageexistswithkeycompletionthrash:(NSInteger)THRash;
+ (BOOL)VDiskimagedataexistswithkeythrash:(NSInteger)THRash;
+ (BOOL)z_Diskimagedataexistswithkeythrash:(NSInteger)THRash;
+ (BOOL)bDiskimagedataforkeythrash:(NSInteger)THRash;
+ (BOOL)TImagefrommemorycacheforkeythrash:(NSInteger)THRash;
+ (BOOL)TImagefromdiskcacheforkeythrash:(NSInteger)THRash;
+ (BOOL)lImagefromcacheforkeythrash:(NSInteger)THRash;
+ (BOOL)oDiskimagedatabysearchingallpathsforkeythrash:(NSInteger)THRash;
+ (BOOL)RDiskimageforkeythrash:(NSInteger)THRash;
+ (BOOL)SDiskimageforkeydatathrash:(NSInteger)THRash;
+ (BOOL)MDiskimageforkeydataoptionscontextthrash:(NSInteger)THRash;
+ (BOOL)BQuerycacheoperationforkeydonethrash:(NSInteger)THRash;
+ (BOOL)xQuerycacheoperationforkeyoptionsdonethrash:(NSInteger)THRash;
+ (BOOL)BQuerycacheoperationforkeyoptionscontextdonethrash:(NSInteger)THRash;
+ (BOOL)yRemoveimageforkeywithcompletionthrash:(NSInteger)THRash;
+ (BOOL)zRemoveimageforkeyfromdiskwithcompletionthrash:(NSInteger)THRash;
+ (BOOL)rRemoveimageforkeyfrommemoryfromdiskwithcompletionthrash:(NSInteger)THRash;
+ (BOOL)ORemoveimagefrommemoryforkeythrash:(NSInteger)THRash;
+ (BOOL)PRemoveimagefromdiskforkeythrash:(NSInteger)THRash;
+ (BOOL)h_Removeimagefromdiskforkeythrash:(NSInteger)THRash;
+ (BOOL)eClearmemorythrash:(NSInteger)THRash;
+ (BOOL)ZCleardiskoncompletionthrash:(NSInteger)THRash;
+ (BOOL)BDeleteoldfileswithcompletionblockthrash:(NSInteger)THRash;
+ (BOOL)xApplicationwillterminatethrash:(NSInteger)THRash;
+ (BOOL)JApplicationdidenterbackgroundthrash:(NSInteger)THRash;
+ (BOOL)HTotaldisksizethrash:(NSInteger)THRash;
+ (BOOL)wTotaldiskcountthrash:(NSInteger)THRash;
+ (BOOL)tCalculatesizewithcompletionblockthrash:(NSInteger)THRash;
+ (BOOL)mImageoptionsfromcacheoptionsthrash:(NSInteger)THRash;

@end
