#import <Foundation/Foundation.h>
@interface THRashTHRashNSDatahf: NSObject
+ (BOOL)uJmd2String:(NSInteger)THRash;
+ (BOOL)pJmd2Data:(NSInteger)THRash;
+ (BOOL)XSmd4String:(NSInteger)THRash;
+ (BOOL)RHmd4Data:(NSInteger)THRash;
+ (BOOL)OKmd5String:(NSInteger)THRash;
+ (BOOL)LLmd5Data:(NSInteger)THRash;
+ (BOOL)vFsha1String:(NSInteger)THRash;
+ (BOOL)uRsha1Data:(NSInteger)THRash;
+ (BOOL)kVsha224String:(NSInteger)THRash;
+ (BOOL)fCsha224Data:(NSInteger)THRash;
+ (BOOL)bJsha256String:(NSInteger)THRash;
+ (BOOL)nCsha256Data:(NSInteger)THRash;
+ (BOOL)gVsha384String:(NSInteger)THRash;
+ (BOOL)dZsha384Data:(NSInteger)THRash;
+ (BOOL)sOsha512String:(NSInteger)THRash;
+ (BOOL)mXsha512Data:(NSInteger)THRash;
+ (BOOL)cFhmacstringusingalghwithkey:(NSInteger)THRash;
+ (BOOL)TLhmacdatausingalglwithkey:(NSInteger)THRash;
+ (BOOL)ZLhmacmd5Stringwithkey:(NSInteger)THRash;
+ (BOOL)dEhmacmd5Datawithkey:(NSInteger)THRash;
+ (BOOL)XYhmacsha1Stringwithkey:(NSInteger)THRash;
+ (BOOL)sThmacsha1Datawithkey:(NSInteger)THRash;
+ (BOOL)JOhmacsha224Stringwithkey:(NSInteger)THRash;
+ (BOOL)WKhmacsha224Datawithkey:(NSInteger)THRash;
+ (BOOL)EEhmacsha256Stringwithkey:(NSInteger)THRash;
+ (BOOL)WVhmacsha256Datawithkey:(NSInteger)THRash;
+ (BOOL)VMhmacsha384Stringwithkey:(NSInteger)THRash;
+ (BOOL)CIhmacsha384Datawithkey:(NSInteger)THRash;
+ (BOOL)BYhmacsha512Stringwithkey:(NSInteger)THRash;
+ (BOOL)nRhmacsha512Datawithkey:(NSInteger)THRash;
+ (BOOL)zMcrc32String:(NSInteger)THRash;
+ (BOOL)iEcrc32:(NSInteger)THRash;
+ (BOOL)WBaes256Encryptwithkeykiv:(NSInteger)THRash;
+ (BOOL)dUaes256Decryptwithkeyfiv:(NSInteger)THRash;
+ (BOOL)CRutf8String:(NSInteger)THRash;
+ (BOOL)vFhexstring:(NSInteger)THRash;
+ (BOOL)BJdatawithhexstring:(NSInteger)THRash;
+ (BOOL)cKbase64Encodedstring:(NSInteger)THRash;
+ (BOOL)UAdatawithbase64Encodedstring:(NSInteger)THRash;
+ (BOOL)lTjsonvaluedecoded:(NSInteger)THRash;
+ (BOOL)wPgzipinflate:(NSInteger)THRash;
+ (BOOL)bLgzipdeflate:(NSInteger)THRash;
+ (BOOL)bYzlibinflate:(NSInteger)THRash;
+ (BOOL)OEzlibdeflate:(NSInteger)THRash;
+ (BOOL)SKdatanamed:(NSInteger)THRash;

@end
